from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
import build_report as br  # noqa: E402
import report_inputs as ri  # noqa: E402

REPORTS = br.ROOT / "reports"

# ---- synthetic mini artifacts (invented numbers, same shape as the real files) -----------------

GATE_MD = """# Merge-rule gate

## R1 / R2 TRAIN verdict (40 docs)

| rule | fixed | broken | neutral | net | d OVERALL (pts) | 95% CI (pts) | verdict |
|---|---|---|---|---|---|---|---|
| R1 | 8 | 0 | 0 | 8 | +0.35 | [+0.10, +0.63] | SHIP |
| R2 | 20 | 1 | 0 | 19 | +0.84 | [+0.45, +1.30] | SHIP |
| R2-ocrfree | 2 | 0 | 0 | 2 | +0.01 | [+0.00, +0.02] | DO NOT SHIP |

### R1: SHIP

| group | group n (docs) | fixed | broken | neutral | net |
|---|---|---|---|---|---|
| wb_g01 | 11 | 2 | 0 | 0 | 2 |

## R3 supplier-held-out, 3 folds pooled, 50 docs

| rule | fixed | broken | neutral | net | d OVERALL (pts) | 95% CI (pts) | verdict |
|---|---|---|---|---|---|---|---|
| R3 (supplier-held-out, folds pooled) | 50 | 0 | 1 | 50 | +5.40 | [+3.86, +7.03] | SHIP |
| R3 (all-gold shapes, in-sample) | 50 | 0 | 1 | 50 | +5.40 | [+3.86, +7.03] | no verdict |

### R3 (supplier-held-out, folds pooled): SHIP

| group | group n (docs) | fixed | broken | neutral | net |
|---|---|---|---|---|---|
| inv_g01 | 23 | 0 | 0 | 0 | 0 |
| inv_g02 | 16 | 4 | 0 | 0 | 4 |
| inv_g03 | 19 | 0 | 0 | 5 | 0 |
| inv_g04 | 32 | 30 | 0 | 0 | 30 |
| inv_g05 | 22 | 6 | 0 | 0 | 6 |
| inv_g06 | 25 | 10 | 0 | 0 | 10 |

### R3 (all-gold shapes, in-sample): no verdict

| group | group n (docs) | fixed | broken | neutral | net |
|---|---|---|---|---|---|
| inv_g01 | 23 | 99 | 0 | 0 | 99 |
"""

REPLAY_MD = """# Replay

## (a) HONEST

| slice | docs | base OVERALL | v1 OVERALL | d OVERALL (pts) | 95% CI (pts) |
|---|---|---|---|---|---|
| all | 500 | 76.58 | 83.60 | +7.02 | [+5.42, +8.90] |
| invoice | 400 | 76.12 | 81.84 | +5.73 | [+4.07, +7.56] |

Per rule:

| rule | fixed | broken |
|---|---|---|
| R1 | 12 | 0 |
"""

LAYOUT_MD = """# Clusters

## 3. Unseen-layout share of the test split

| doc type | k | threshold | seen-dist median |
|---|---|---|---|
| invoice | 30 | 1.437 | 0.497 |
| waybill | 18 | 0.148 | 0.021 |

| doc type | test docs | primary: centre distance > threshold, count (share) [Wilson 95%] |
|---|---|---|
| invoice | 160 | 40 (25.0%) [0.18, 0.31] |
| waybill | 40 | 1 (2.5%) [0.00, 0.13] |

## 2. Test doc type

Test split (200 docs): 160 invoice-like, 40 waybill-like by the rule.
"""

ROW_ERRORS_MD = """# Row errors

**Provenance.** Run `dev100_run_x` (Qwen), generated by a script.

## X4. Cause -> fix class -> ORACLE recoverable points

| cause | n rows / cells | fix class | recoverable OVERALL points [95% CI] (ORACLE upper bound) |
|---|---|---|---|
| rows: column_shift | 65 gold / 65 pred (7 docs) | ctx | +2.82 [+0.65, +5.50] |
| rows: spn_misread | 66 gold / 66 pred (28 docs) | ft | +5.46 [+3.65, +7.38] |
| paired-row slot: po_in_cpn_slot | 52 paired rows | ft | +2.66 [+0.48, +5.68] |
"""


def _est(p: float, lo: float, hi: float) -> dict[str, float]:
    return {"point": p, "lo": lo, "hi": hi}


def _tau_row(pop: str, t: float, prec: Any, cov: float, n: int = 100) -> dict[str, Any]:
    nan = float("nan")
    return {
        "population": pop,
        "target": t,
        "slice": "all",
        "scheme": "nested",
        "n": n,
        "precision_accepted": prec if prec is not None else _est(nan, nan, nan),
        "accepted_share": _est(cov, cov - 0.01, cov + 0.01),
    }


def _v2() -> dict[str, Any]:
    spec = {
        "header": (_est(0.99, 0.98, 1.0), 1.0),  # attained
        "supplier_part_number": (_est(0.979, 0.96, 0.99), 0.74),  # near-miss at 0.98
        "customer_part_number": (_est(0.0, 0.0, 0.0), 0.03),  # coverage under the minimum
        "purchase_order": (None, 0.0),  # nothing auto-accepted
        "quantity": (_est(0.72, 0.47, 0.92), 0.013),
        "all_per_type_tau": (_est(0.90, 0.88, 0.92), 0.4),  # CI misses the target
    }
    tau = [_tau_row(p, t, *spec[p]) for p in spec for t in (0.95, 0.98, 0.99)]
    doc = [_tau_row("doc", t, _est(0.9, 0.8, 0.97), 0.08, n=500) for t in (0.95, 0.98)]
    # one ECE per group: 0.01, 0.02, ... in this order (all_per_type_tau lives under all_emitted)
    ece_groups = [*(p for p in spec if p != "all_per_type_tau"), "doc", "all_emitted"]
    return {
        "slice_docs": {"all": 500, "dev": 100},
        "tau": tau,
        "doc_level": doc,
        "doc_attainability": {"0.95": {"attained": False}, "0.98": {"attained": False}},
        "provenance": {"shapes_equal": {"0": True, "1": True, "2": False}},  # JSON str keys
        "calibration": [
            {"slice": "all", "group": g, "ece_width15": 0.01 * (i + 1)}
            for i, g in enumerate(ece_groups)
        ],
    }


def _v1() -> dict[str, Any]:
    def ov(d: float, lo: float, hi: float) -> dict[str, Any]:
        return {"all": {"OVERALL": {"delta": d, "lo": lo, "hi": hi}}}

    ff = {
        "redaction": {"null_fields": 35, "filled": 0},
        "absent_line": {"null_fields": 157, "filled": 3},
    }
    return {
        "null_policy_doc_level": {
            "header_and_rows": {
                "all": {
                    "OVERALL": {"delta": -0.013, "lo": -0.02, "hi": -0.006},
                    "false_fills_raw": ff,
                }
            },
            "header_only": ov(0.0, 0.0, 0.0),
        }
    }


def _ablation() -> dict[str, Any]:
    def rung(i: str, vs: float | None) -> dict[str, Any]:
        r: dict[str, Any] = {
            "id": i,
            "label": f"label {i}",
            "OVERALL": 0.76,
            "OVERALL_ci": [0.74, 0.78],
            "false_fill": 0.03,
            "false_fill_ci": [0.01, 0.06],
        }
        if vs is not None:
            r["vs_prev"] = {"OVERALL": {"delta": vs, "lo": vs - 0.01, "hi": vs + 0.01}}
        return r

    return {
        "meta": {"n_docs": 500, "n_train": 400, "n_dev": 100},
        "ladder": {"rungs": [rung("R0", None), rung("R2b", 0.005)]},
    }


# ---- markdown table parser -------------------------------------------------------------------


def test_parse_md_tables_headings_and_rows() -> None:
    tables = ri.parse_md_tables(GATE_MD)
    assert [t.heading for t in tables][:2] == ["R1 / R2 TRAIN verdict (40 docs)", "R1: SHIP"]
    assert tables[0].header[:3] == ["rule", "fixed", "broken"]
    assert len(tables[0].rows) == 3


def test_parse_rejects_ragged_row() -> None:
    bad = "## H\n\n| a | b |\n|---|---|\n| 1 | 2 | 3 |\n"
    with pytest.raises(ri.MdFormatError, match="3 cells"):
        ri.parse_md_tables(bad)


def test_find_table_fails_loudly_on_missing_heading_or_column() -> None:
    tables = ri.parse_md_tables(GATE_MD)
    with pytest.raises(ri.MdFormatError):
        ri.find_table(tables, r"^No such heading", ("rule",))
    with pytest.raises(ri.MdFormatError):
        ri.find_table(tables, r"^R1 / R2 TRAIN", ("rule", "renamed column"))
    with pytest.raises(ri.MdFormatError):
        ri.row_where(tables[0], "rule", "R9")


def test_pts_to_delta_parses_and_rejects() -> None:
    assert ri.pts_to_delta("+0.35", "[+0.10, +0.63]", "x") == {
        "delta": 0.0035,
        "lo": 0.001,
        "hi": 0.0063,
    }
    with pytest.raises(ri.MdFormatError):
        ri.pts_to_delta("n/a", "[+0.10, +0.63]", "x")
    with pytest.raises(ri.MdFormatError):
        ri.pts_to_delta("+0.35", "0.1 to 0.6", "x")
    with pytest.raises(ri.MdFormatError):
        ri.pts_to_delta("+9.00", "[+0.10, +0.63]", "x")  # point outside its own interval


# ---- rules -----------------------------------------------------------------------------------


def test_rules_from_gate_md_counts_deltas_and_concentration() -> None:
    r = ri.rules_from_gate_md(GATE_MD)
    assert (r["train_docs"], r["r3_docs"]) == (40, 50)
    assert (r["r1"]["fixed"], r["r1"]["broken"]) == (8, 0)
    assert r["r2"]["broken"] == 1
    assert r["r2_ocrfree"]["fixed"] == 2
    assert r["r2"]["delta"]["delta"] == pytest.approx(0.0084)
    r3 = r["r3"]
    assert r3["total_fixed"] == r3["fixed"] == 50
    assert r3["top3_fixed"] == 30 + 10 + 6 and r3["top_n"] == 3
    assert r3["groups_total"] == 6
    assert r3["groups_touched"] == 5  # g01 untouched; g03 counted via its neutral cells


def test_rules_group_sum_must_match_summary_row() -> None:
    with pytest.raises(ri.MdFormatError, match="sum to"):
        ri.rules_from_gate_md(GATE_MD.replace("| inv_g06 | 25 | 10 |", "| inv_g06 | 25 | 11 |"))


def test_rules_fail_on_renamed_heading_or_missing_row() -> None:
    with pytest.raises(ri.MdFormatError):
        ri.rules_from_gate_md(GATE_MD.replace("TRAIN verdict", "TRAINING verdict"))
    with pytest.raises(ri.MdFormatError):
        ri.rules_from_gate_md(GATE_MD.replace("| R2-ocrfree |", "| R2-ocr-free |"))
    with pytest.raises(ri.MdFormatError):
        ri.rules_from_gate_md(GATE_MD.replace("(40 docs)", "(forty docs)"))


def test_combined_delta_from_replay() -> None:
    d = ri.combined_delta_from_replay_md(REPLAY_MD)
    assert d == {"delta": 0.0702, "lo": 0.0542, "hi": 0.089}
    with pytest.raises(ri.MdFormatError):
        ri.combined_delta_from_replay_md(REPLAY_MD.replace("(a) HONEST", "(b) HONEST"))
    with pytest.raises(ri.MdFormatError):
        ri.combined_delta_from_replay_md(REPLAY_MD.replace("| all |", "| everything |"))


# ---- failure / clusters ----------------------------------------------------------------------


def test_failure_from_row_errors() -> None:
    f = ri.failure_from_row_errors_md(ROW_ERRORS_MD)
    assert f["run_id"] == "dev100_run_x" and f["n_docs"] == 100
    assert f["causes"]["spn_misread"]["rows"] == 66 and f["causes"]["spn_misread"]["docs"] == 28
    assert f["causes"]["column_shift"]["oracle"]["delta"] == pytest.approx(0.0282)
    assert "docs" not in f["causes"]["po_in_cpn_slot"]
    assert f["causes"]["po_in_cpn_slot"]["rows"] == 52
    with pytest.raises(ri.MdFormatError):
        ri.failure_from_row_errors_md(ROW_ERRORS_MD.replace("rows: column_shift", "rows: shifted"))
    with pytest.raises(ri.MdFormatError):
        ri.failure_from_row_errors_md(ROW_ERRORS_MD.replace("**Provenance.**", "Provenance:"))
    with pytest.raises(ri.MdFormatError):  # a run id that does not name its doc count
        ri.failure_from_row_errors_md(ROW_ERRORS_MD.replace("dev100_run_x", "some_run"))


def test_clusters_from_layout_md() -> None:
    c = ri.clusters_from_layout_md(LAYOUT_MD)
    assert c == {"n_test_docs": 200, "n_clusters": 30, "estimated_unseen_share": 0.25}
    with pytest.raises(ri.MdFormatError):
        ri.clusters_from_layout_md(LAYOUT_MD.replace("Test split", "Test set"))
    with pytest.raises(ri.MdFormatError):
        ri.clusters_from_layout_md(LAYOUT_MD.replace("40 (25.0%)", "forty"))
    with pytest.raises(ri.MdFormatError):
        ri.clusters_from_layout_md(LAYOUT_MD.replace("40 (25.0%)", "400 (25.0%)"))


# ---- calibration / ablation / cost -----------------------------------------------------------


def test_calibration_statuses_na_ece_and_policy() -> None:
    c = ri.calibration_from_v2(_v2(), _v1())
    t = c["types"]
    assert t["header"]["t98"]["status"] == "attained"
    assert t["supplier_part_number"]["t98"]["status"] == "near-miss"
    assert t["customer_part_number"]["t98"]["status"] == "NOT ATTAINABLE"
    assert t["purchase_order"]["t98"]["precision"] == "n/a"
    assert t["purchase_order"]["t98"]["status"] == "NOT ATTAINABLE"
    assert t["all_per_type_tau"]["t98"]["status"] == "NOT ATTAINABLE"
    assert t["doc"]["t98"]["status"] == "NOT ATTAINABLE" and "t99" not in t["doc"]
    assert t["header"]["t99"]["coverage"]["point"] == 1.0
    assert t["header"]["n"] == 100 and t["doc"]["n"] == 500
    assert t["header"]["ece"] == pytest.approx(0.01)
    assert t["all_per_type_tau"]["ece"] == pytest.approx(0.07)  # read from the all_emitted group
    assert (c["n_docs"], c["dev_docs"], c["min_coverage"]) == (500, 100, 0.05)
    assert (c["shapes_equal_folds"], c["shapes_folds"]) == (2, 3)
    assert c["row_null_policy"]["delta"]["delta"] == -0.013
    assert c["row_null_policy"]["header_only_delta"]["delta"] == 0.0
    ff = c["false_fill"]
    assert ff["redaction"]["n"] == 35 and ff["redaction"]["rate"]["point"] == 0.0
    assert 0.0 < ff["redaction"]["rate"]["hi"] < 0.11  # Wilson upper bound for 0 / 35
    assert ff["absent_line"]["rate"]["point"] == pytest.approx(3 / 157)
    json.dumps(c, allow_nan=False)  # no NaN leaks into the JSON


def test_calibration_without_v1_has_no_policy_and_missing_row_fails() -> None:
    c = ri.calibration_from_v2(_v2())
    assert "row_null_policy" not in c and "false_fill" not in c
    v2 = _v2()
    v2["tau"] = [
        r for r in v2["tau"] if not (r["population"] == "quantity" and r["target"] == 0.99)
    ]
    with pytest.raises(br.ReportError, match="quantity"):
        ri.calibration_from_v2(v2)


def test_wilson_bounds() -> None:
    w = ri.wilson(5, 10)
    assert w["point"] == 0.5 and w["lo"] < 0.5 < w["hi"]
    assert math.isclose(w["lo"], 1 - w["hi"], abs_tol=1e-9)
    with pytest.raises(br.ReportError):
        ri.wilson(1, 0)


def test_ablation_from_json() -> None:
    a = ri.ablation_from_json(_ablation())
    assert a["split"] == "400 train + 100 dev docs, zero-shot run"
    bad = _ablation()
    bad["meta"]["n_dev"] = 99
    with pytest.raises(br.ReportError):
        ri.ablation_from_json(bad)
    assert a["n_docs"] == 500 and [r["name"] for r in a["rungs"]] == [
        "R0 label R0",
        "R2b label R2b",
    ]
    assert a["rungs"][0]["delta_vs_prev"] is None
    assert a["rungs"][1]["delta_vs_prev"]["delta"] == 0.005
    assert a["rungs"][1]["overall"] == {"point": 0.76, "lo": 0.74, "hi": 0.78}


def test_cost_pages_per_doc_and_usd(tmp_path: Path) -> None:
    (tmp_path / "metrics.json").write_text(json.dumps({"n_docs": 10, "n_pages": 15}), "utf-8")
    lat = {"s_per_page_mean": 3.6}
    c = ri.cost_from_run(tmp_path, None, lat)
    assert c == {"pages_per_doc": 1.5}  # no GPU / price known: nothing else invented
    c = ri.cost_from_run(tmp_path, {"hourly_usd": 0.5, "timing_basis": "x"}, lat)
    assert c["usd_per_1000_docs"] == pytest.approx(3.6 * 1.5 * 1000 / 3600 * 0.5)
    assert c["timing_basis"] == "x"


# ---- end to end: converters -> manifest -> template ------------------------------------------


def _write(p: Path, text: str) -> Path:
    p.write_text(text, encoding="utf-8")
    return p


def test_end_to_end_resolves_the_new_keys_and_only_expected_pending(tmp_path: Path) -> None:
    run = tmp_path / "run"
    run.mkdir()
    trace = [{"pages": [{"meta": {"latency_s": s, "peak_vram_bytes": 2**30}}]} for s in (1, 2, 3)]
    _write(run / "trace.jsonl", "\n".join(json.dumps(x) for x in trace))
    _write(run / "metrics.json", json.dumps({"n_docs": 2, "n_pages": 3}))
    v2d, v1d = tmp_path / "v2", tmp_path / "v1"
    v2d.mkdir()
    v1d.mkdir()
    _write(v2d / "calibration_v2.json", json.dumps(_v2()))
    _write(v1d / "calibration.json", json.dumps(_v1()))
    out = tmp_path / "out"
    rc = ri.main(
        [
            "--out-dir", str(out),
            "--run-dir", str(run),
            "--calibration-v2-dir", str(v2d),
            "--calibration-dir", str(v1d),
            "--ablation-json", str(_write(tmp_path / "abl.json", json.dumps(_ablation()))),
            "--v1-replay-md", str(_write(tmp_path / "v1.md", REPLAY_MD)),
            "--rule-gate-md", str(_write(tmp_path / "gate.md", GATE_MD)),
            "--layout-md", str(_write(tmp_path / "lay.md", LAYOUT_MD)),
            "--row-errors-md", str(_write(tmp_path / "re.md", ROW_ERRORS_MD)),
            "--value", "report_date=2000-01-01",
        ]
    )  # fmt: skip
    assert rc == 0
    man = json.loads((out / "inputs.json").read_text("utf-8"))
    assert set(man["sources"]) == {
        "ablation", "failure", "clusters", "calibration", "rules", "cost"
    }  # fmt: skip
    assert {s["status"] for s in man["sources"].values()} <= {"unverified", "estimated"}
    ctx = br.load_manifest(out / "inputs.json")
    text, left = br.fill(br.TEMPLATE.read_text(encoding="utf-8"), ctx)
    assert "R3 disclosure" in text
    pending = set(left)
    # nothing the converters claim to produce may stay pending
    for prefix in (
        "rules.",
        "failure.",
        "ablation.",
        "calibration.types",
        "latency.",
        "cost.pages",
    ):
        assert not [p for p in pending if p.startswith(prefix)], pending
    for key in ("row_null_policy", "false_fill", "dev_docs", "n_docs", "min_coverage"):
        assert f"calibration.{key}" not in pending
    # no model was ever run on the synthetic-redaction pages: produced by nothing, by design
    assert "calibration.synthetic_redaction.null_rate" in pending
    assert "clusters.predicted_review_rate" in pending
    assert "values.model_state" in pending


def test_outputs_hold_aggregates_only(tmp_path: Path) -> None:
    c = ri.calibration_from_v2(_v2(), _v1())

    def leaves(x: Any) -> list[Any]:
        if isinstance(x, dict):
            return [v for y in x.values() for v in leaves(y)]
        return [x]

    # every leaf is a number or one of the fixed status / marker strings
    strings = {v for v in leaves(c) if isinstance(v, str)}
    assert strings <= {"attained", "near-miss", "NOT ATTAINABLE", "n/a"}


def test_failures_are_reported_not_raised_from_main(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    bad = _write(tmp_path / "gate.md", GATE_MD.replace("TRAIN verdict", "other"))
    assert ri.main(["--out-dir", str(tmp_path / "o"), "--rule-gate-md", str(bad)]) == 1
    assert "error:" in capsys.readouterr().err
    assert (
        ri.main(["--out-dir", str(tmp_path / "o"), "--ablation-json", str(tmp_path / "no.json")])
        == 1
    )


# ---- the real committed markdown still parses ------------------------------------------------


@pytest.mark.skipif(not (REPORTS / "rule_gate.md").is_file(), reason="reports not present")
def test_real_markdown_parses_and_is_internally_consistent() -> None:
    r = ri.rules_from_gate_md((REPORTS / "rule_gate.md").read_text("utf-8"))
    r3 = r["r3"]
    assert r3["total_fixed"] == r3["fixed"]
    assert r3["top3_fixed"] <= r3["total_fixed"]
    assert 0 < r3["groups_touched"] <= r3["groups_total"]
    ri.combined_delta_from_replay_md((REPORTS / "v1_replay.md").read_text("utf-8"))
    ri.clusters_from_layout_md((REPORTS / "layout_test_clusters.md").read_text("utf-8"))
    ri.failure_from_row_errors_md((REPORTS / "row_errors.md").read_text("utf-8"))


# ---- measured cost and latency ---------------------------------------------------------------


def _v0() -> dict[str, Any]:
    return {
        "docs": {"n_docs": 10, "n_pages": 20},
        "timings": {"model_time_s": 200.0, "wall_clock_s": 300.0, "smoke_s": 30.0},
        "dependencies": {"gpu": "Tesla T4"},
        "batch_size": 8,
    }


def _ocr() -> dict[str, Any]:
    return {
        "engine": "paddleocr",
        "device": "gpu",
        "pages": 20,
        "seconds_total": 40.0,
        "seconds_per_page_mean": 2.0,
        "seconds_per_page_p95": 3.0,
        "wall_clock_s_all_sessions": 60.0,
    }


def _train_status() -> dict[str, Any]:
    return {
        "state": "complete",
        "total_steps": 3,
        "peak_vram_gib": 11.0,
        "n_train_pages": 9,
        "precision": "bf16",
    }


_STEPS = [{"step": i, "seconds": 10.0 * i} for i in (1, 2, 3)]
_TRAIN_SESSIONS = [
    {"seconds": None, "exit_code": None},
    {"seconds": None, "exit_code": None},
    {"seconds": 50.0, "exit_code": 0},
]
RES_MD = """# sweep

## Per-resolution results (paired against the control)

| max_pixels | s/page |
|---|---|
| 1000 (control) | 40.0 |
| 1500 | 41.0 |
| 2000 | 42.0 |
"""
RES_MD = RES_MD.replace("1000 (control)", "1310720 (control)").replace(
    "| 2000 |", "| 2196480 |"
)  # the real max_pixels values the converter looks for


def test_cost_inference_and_submission_from_manifest() -> None:
    inf = ri.cost_inference_from_manifest(_v0())
    assert inf["gpu"] == "Tesla T4" and inf["batch_size"] == 8
    assert inf["test"]["s_per_page"] == 10.0 and inf["test"]["pages_per_doc"] == 2.0
    sub = ri.submission_cost(inf, ri.cost_ocr_from_timing(_ocr()))
    assert sub["vlm_h"] == pytest.approx(200 / 3600)
    assert sub["full_h"] == pytest.approx(240 / 3600)
    assert sub["reuse_ocr_h"] == pytest.approx(40 / 3600) and sub["reuse_vlm_h"] == 0.0


def test_cost_converters_fail_loudly_on_a_changed_shape() -> None:
    bad = _v0()
    del bad["timings"]["model_time_s"]
    with pytest.raises(br.ReportError, match="timings.model_time_s"):
        ri.cost_inference_from_manifest(bad)
    bad = _v0()
    bad["dependencies"]["gpu"] = ""
    with pytest.raises(br.ReportError, match="gpu"):
        ri.cost_inference_from_manifest(bad)
    bad = _v0()
    bad["docs"]["n_pages"] = 0
    with pytest.raises(br.ReportError, match="positive"):
        ri.cost_inference_from_manifest(bad)
    bad_ocr = _ocr()
    del bad_ocr["seconds_per_page_p95"]
    with pytest.raises(br.ReportError, match="seconds_per_page_p95"):
        ri.cost_ocr_from_timing(bad_ocr)


def test_cost_train_is_the_step_sum_and_counts_interrupted_sessions() -> None:
    t = ri.cost_train_from_run(_STEPS, _TRAIN_SESSIONS, _train_status())
    assert t["step_seconds_sum"] == 60.0 and t["s_per_step"] == 20.0
    assert t["hours"] == pytest.approx(60 / 3600)
    assert (t["sessions"], t["interrupted_sessions"]) == (3, 2)
    assert t["peak_vram_gib"] == 11.0 and t["precision"] == "bf16"
    with pytest.raises(br.ReportError, match="steps are not exactly"):
        ri.cost_train_from_run(_STEPS[:2], _TRAIN_SESSIONS, _train_status())
    with pytest.raises(br.ReportError, match="steps are not exactly"):
        ri.cost_train_from_run([*_STEPS, _STEPS[0]], _TRAIN_SESSIONS, _train_status())
    with pytest.raises(br.ReportError, match="complete"):
        ri.cost_train_from_run(_STEPS, _TRAIN_SESSIONS, {**_train_status(), "state": "running"})
    with pytest.raises(br.ReportError, match="exit 0"):
        ri.cost_train_from_run(_STEPS, _TRAIN_SESSIONS[:2], _train_status())


def test_cost_zeroshot_and_oof_sessions() -> None:
    z = ri.cost_zeroshot_from_run([{"seconds": 100.0}, {"seconds": 50.0}], {"n_pages": 30})
    assert z == {"session_s": 150.0, "pages": 30, "s_per_page": 5.0}
    with pytest.raises(br.ReportError, match="unfinished"):
        ri.cost_zeroshot_from_run([{"seconds": None}], {"n_pages": 30})
    o = ri.cost_oof_from_run(
        [{"seconds": 360.0}], {"oof": {"merge": {"load_and_merge_s": 5.0}}}, {"n_pages": 12}
    )
    assert o["hours"] == pytest.approx(0.1) and o["s_per_page"] == 30.0
    assert o["load_and_merge_s"] == 5.0
    with pytest.raises(br.ReportError, match="load_and_merge_s"):
        ri.cost_oof_from_run([{"seconds": 1.0}], {"oof": {}}, {"n_pages": 1})


def test_native_estimate_scales_the_measured_time_by_the_sweep_ratio() -> None:
    f = ri.res_sweep_factor(RES_MD)
    assert f["factor"] == pytest.approx(42.0 / 40.0)
    est = ri.native_estimate(f, ri.cost_inference_from_manifest(_v0()))
    assert est["native_s_per_page"] == pytest.approx(10.0 * 1.05)
    assert est["native_vlm_h"] == pytest.approx(200 * 1.05 / 3600)
    with pytest.raises(ri.MdFormatError):
        ri.res_sweep_factor(RES_MD.replace("2196480", "2500"))
    with pytest.raises(ri.MdFormatError):
        ri.res_sweep_factor(RES_MD.replace("42.0", "n/a"))


def test_measured_cost_end_to_end_leaves_only_the_price_pending(tmp_path: Path) -> None:
    run = tmp_path / "run"
    run.mkdir()
    trace = [{"pages": [{"meta": {"latency_s": s, "peak_vram_bytes": 2**30}}]} for s in (1, 2, 3)]
    _write(run / "trace.jsonl", "\n".join(json.dumps(x) for x in trace))
    _write(run / "metrics.json", json.dumps({"n_docs": 2, "n_pages": 3}))
    _write(run / "sessions.json", json.dumps([{"seconds": 30.0}]))
    _write(run / "manifest.json", json.dumps({"batch_size": 8}))
    tr = tmp_path / "train"
    tr.mkdir()
    _write(tr / "metrics.jsonl", "\n".join(json.dumps(s) for s in _STEPS))
    _write(tr / "sessions.json", json.dumps(_TRAIN_SESSIONS))
    _write(tr / "train_status.json", json.dumps(_train_status()))
    oof = tmp_path / "oof"
    oof.mkdir()
    _write(oof / "sessions.json", json.dumps([{"seconds": 360.0}]))
    _write(oof / "manifest.json", json.dumps({"oof": {"merge": {"load_and_merge_s": 5.0}}}))
    _write(oof / "metrics.json", json.dumps({"n_pages": 12}))
    out = tmp_path / "out"
    args = [
        "--out-dir", str(out),
        "--run-dir", str(run),
        "--submission-manifest", str(_write(tmp_path / "v0.json", json.dumps(_v0()))),
        "--ocr-timing", str(_write(tmp_path / "ocr.json", json.dumps(_ocr()))),
        "--train-dir", str(tr),
        "--oof-dir", str(oof),
        "--res-sweep-md", str(_write(tmp_path / "res.md", RES_MD)),
    ]  # fmt: skip
    assert ri.main(args) == 0
    man = json.loads((out / "inputs.json").read_text("utf-8"))
    assert man["sources"]["cost"]["status"] == "unverified"  # measured, not yet re-computed
    assert man["sources"]["cost_est"]["status"] == "estimated"
    text, left = br.fill(
        br.TEMPLATE.read_text(encoding="utf-8"), br.load_manifest(out / "inputs.json")
    )
    assert [p for p in left if p.startswith(("cost.", "latency."))] == []
    assert {p for p in left if p.startswith("cost_est.")} == {
        "cost_est.hourly_usd",
        "cost_est.price_source",
        "cost_est.usd_per_1000_docs",
    }
    assert "ESTIMATE, UNVERIFIED" in text and "UNMEASURED" in text
    # a price supplied by hand fills the estimate namespace and computes USD per 1,000 docs
    price = _write(tmp_path / "price.json", json.dumps({"hourly_usd": 0.5, "price_source": "x"}))
    assert ri.main([*args, "--cost", str(price)]) == 0
    est = json.loads((out / "cost_est.json").read_text("utf-8"))
    assert est["usd_per_1000_docs"] == pytest.approx(2.0 * 1.5 * 1000 / 3600 * 0.5)
    # a given path that does not exist is an error, not a silent skip
    assert ri.main([*args[:-2], "--res-sweep-md", str(tmp_path / "nope.md")]) == 1


REAL = Path("D:/shipdoc")


@pytest.mark.skipif(not (REAL / "submissions" / "v0_42b812b").is_dir(), reason="artifacts absent")
def test_real_cost_artifacts_still_have_the_expected_shape() -> None:
    inf = ri.cost_inference_from_manifest(
        json.loads((REAL / "submissions/v0_42b812b/manifest.json").read_text("utf-8"))
    )
    assert inf["gpu"] == "Tesla T4" and inf["batch_size"] == 8
    ri.cost_ocr_from_timing(
        json.loads((REAL / "submissions/v1_8833c73/ocr_timing.json").read_text("utf-8"))
    )
    ri.res_sweep_factor((REPORTS / "res_sweep.md").read_text("utf-8"))
