"""Append the native-vs-1260 calibrator comparison to ``reports/calibration_v2_native.md`` (CPU).

Reads the ``calibration_v2.json`` of the 1260-token run (the numbers behind
``reports/calibration_v2.md``) and of the native run, and writes a marked block with, per field
type: nested coverage and precision at the 95 / 98 / 99% targets (slice ``all``), AUROC of the v2
model on all its rows, and ECE (15 equal-width bins); plus the model structure and the document
auto-accept verdict. Also states which frozen calibrator serves which submission. Numbers are
copied from the two JSON files, never retyped. UNVERIFIED until a verifier recomputes them.

Run: ``uv run python scripts/calibration_compare_native.py --base-json <1260 json> --native-json
<native json> --out reports/calibration_v2_native.md``
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "<!-- native-vs-1260-begin (generated by scripts/calibration_compare_native.py) -->"
END = "<!-- native-vs-1260-end -->"
POPS = (
    "header",
    "supplier_part_number",
    "customer_part_number",
    "purchase_order",
    "quantity",
    "all_per_type_tau",
    "all_global_tau",
)
TARGETS = (0.95, 0.98, 0.99)
AUROC_GROUPS = (
    "header_all",
    "row.supplier_part_number",
    "row.customer_part_number",
    "row.purchase_order",
    "row.quantity",
)
ECE_GROUPS = (
    "header",
    "supplier_part_number",
    "customer_part_number",
    "purchase_order",
    "quantity",
    "all_emitted",
    "doc",
)


def _pct(x: float | None) -> str:
    return "n/a" if x is None or x != x else f"{100 * x:.1f}"  # x != x: NaN


def tau_cell(res: Mapping[str, Any], pop: str, target: float, sl: str = "all") -> str:
    """``coverage / precision`` (nested, point, %) of a population and target; ``n/a`` if absent."""
    for r in res["tau"]:
        if (
            r["population"] == pop
            and abs(r["target"] - target) < 1e-9
            and r["slice"] == sl
            and r["scheme"] == "nested"
        ):
            return (
                f"{_pct(r['accepted_share']['point'])} / {_pct(r['precision_accepted']['point'])}"
            )
    return "n/a"


def auroc_cell(res: Mapping[str, Any], group: str) -> str:
    """AUROC (point) of the v2 model on all its rows, slice ``all``; ``n/a`` when not computed."""
    for r in res["auroc"]:
        if r["variant"] == "v2_all_rows" and r["slice"] == "all" and r["group"] == group:
            p = r["point"]
            return "n/a" if p is None or p != p else f"{p:.3f}"
    return "n/a"


def ece_cell(res: Mapping[str, Any], group: str) -> str:
    """ECE with 15 equal-width bins, slice ``all``."""
    for r in res["calibration"]:
        if r["slice"] == "all" and r["group"] == group:
            return f"{r['ece_width15']:.3f}"
    return "n/a"


def render(
    base: Mapping[str, Any], native: Mapping[str, Any], base_name: str, native_name: str
) -> str:
    """The comparison block (aggregates only)."""

    def table(head: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
        out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        return "\n".join(out + ["| " + " | ".join(r) + " |" for r in rows]) + "\n"

    w = [
        "## Native calibrator vs the 1260-token calibrator\n",
        f"Sources: 1260 = `{base_name}`, native = `{native_name}` "
        "(`calibration_v2.json` of each).\n",
        "Nested coverage % / nested precision % (point estimates, slice `all`, supplier-fold "
        "nested tau; CIs are in the two calibration_v2 reports):\n",
        table(
            ["population", *[f"{int(100 * t)}% {s}" for t in TARGETS for s in ("1260", "native")]],
            [[p, *[tau_cell(r, p, t) for t in TARGETS for r in (base, native)]] for p in POPS],
        ),
        "AUROC of P(correct), v2 model on all its rows, slice `all` (n/a = fewer than 5 wrong):\n",
        table(
            ["group", "1260", "native"],
            [[g, auroc_cell(base, g), auroc_cell(native, g)] for g in AUROC_GROUPS],
        ),
        "ECE, 15 equal-width bins, slice `all`:\n",
        table(
            ["group", "1260", "native"],
            [[g, ece_cell(base, g), ece_cell(native, g)] for g in ECE_GROUPS],
        ),
        f"Model structure / kind: 1260 {base['model_selection']['chosen_structure']} / "
        f"{base['model_selection']['chosen_kind']}, native "
        f"{native['model_selection']['chosen_structure']} / "
        f"{native['model_selection']['chosen_kind']}. Document auto-accept at 95 / 98%: 1260 "
        f"attained {base['doc_attainability']['0.95']['attained']} / "
        f"{base['doc_attainability']['0.98']['attained']}, native attained "
        f"{native['doc_attainability']['0.95']['attained']} / "
        f"{native['doc_attainability']['0.98']['attained']}.\n",
        "## Which calibrator serves which submission\n",
        "| submission | model run | calibrator file | records `run_config_hash` |\n"
        "|---|---|---|---|\n"
        "| v1 (1260-token ZS + rules) | max_pixels 1310720, config hash `01d87878679ca0fc` | "
        "`meta/calibrator_zs.json` (untouched) | no (frozen before the guard existed) |\n"
        "| v1.5 native (ZS + rules at native resolution) | max_pixels 2196480, config hash "
        "`e4b84ec2809625d5` | `meta/calibrator_zs_native.json` | yes, `e4b84ec2809625d5` |\n\n"
        "`shipdoc.flags.run_stage` refuses a submission whose manifest config hash differs from "
        "the calibrator's recorded `run_config_hash`; the native notebooks must name "
        "`meta/calibrator_zs_native.json` explicitly (`CALIBRATOR_FILE`) and refuse the 1260 file, "
        "which carries no hash.\n",
    ]
    return "\n".join(w)


def merge_block(text: str, block: str) -> str:
    """Replace the marked block of `text`, or append it; the text outside it is never altered."""
    wrapped = f"{BEGIN}\n{block.rstrip()}\n{END}\n"
    if BEGIN in text and END in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END)
        return head + wrapped.rstrip("\n") + tail
    return text.rstrip("\n") + "\n\n" + wrapped


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--base-json", type=Path, required=True)
    ap.add_argument("--native-json", type=Path, required=True)
    ap.add_argument("--out", type=Path, default=ROOT / "reports" / "calibration_v2_native.md")
    a = ap.parse_args(argv)
    base = json.loads(a.base_json.read_text(encoding="utf-8"))
    native = json.loads(a.native_json.read_text(encoding="utf-8"))
    block = render(base, native, base["provenance"]["run"], native["provenance"]["run"])
    a.out.write_text(
        merge_block(a.out.read_text(encoding="utf-8"), block), encoding="utf-8", newline="\n"
    )
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
