"""500-doc native-resolution confirmation of the 06 sweep (CPU only, no model is called).

Compares the native zero-shot run (``max_pixels`` 2196480, 2145 visual tokens) with the 1260-token
zero-shot run on the SAME 500 train + dev documents, with the unmodified scorer and the paired
doc-level bootstrap (``shipdoc.eval.paired_bootstrap``, 2000 resamples, seed 42). Three views:

1. RAW vs RAW (``predictions.json`` of both runs): OVERALL / header accuracy / row F1 /
   documents fully correct / false-fill, overall and per slice (scanned / digital, invoice /
   waybill, multipage / single page, train / dev), plus the part-number misread count
   (``ressweep.doc_spn_misreads``, the 06 definition, gold rows placed on pages with the OCR
   cache) with a paired bootstrap CI of the count difference.
2. RULES: native ZS + rules vs native raw, and native ZS + rules vs the 1260 ZS + rules (v1),
   both through the production path (``replay_v1_check.production``) with the HONEST per-fold R3
   shapes (supplier-held-out) and with the frozen shipping shapes (in-sample).
3. The 40-document slice of ``splits/spike40.json`` taken from the two 500-doc runs, set beside the
   06 sweep result (``ressweep_result.json``) as a directional check only: the sweep ran at batch
   size 1 on its own runs, these runs at batch 8 (1260) and 4 (native).

This is the one place that compares runs of different resolution ON PURPOSE, so the guard of
``shipdoc.runcompat`` (which refuses it everywhere else) is not used; ``assert_cross_resolution``
instead demands that the two runs differ in config hash (and resolve to the two expected
``max_pixels``) while sharing everything else that matters: model id and revision, seed, document
set. Aggregates and counts only; no gold or predicted value is read into any output. All numbers
are UNVERIFIED until a verifier recomputes them.

Run: ``uv run python scripts/native_confirm.py --native-run <native run> --base-run <1260 run>``
(writes the block between the ``native500`` markers of ``reports/res_sweep.md``; the text above
the block is never touched).
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from types import ModuleType
from typing import Any

from shipdoc import eval as ev
from shipdoc import locate, paths, ressweep
from shipdoc import meta as meta_mod
from shipdoc.postrules import RuleConfig, load_slot_shapes
from shipdoc.replay import read_trace
from shipdoc.runcompat import manifest_config_hash, resolve_max_pixels
from shipdoc.runmeta import read_manifest

ROOT = Path(__file__).resolve().parents[1]
N_BOOT = 2000
SEED = 42
NATIVE_MAX_PIXELS = 2196480
BASE_MAX_PIXELS = 1310720
BEGIN = "<!-- native500-begin (generated by scripts/native_confirm.py) -->"
END = "<!-- native500-end -->"
TITLE = "## 500-doc native confirmation"
METRIC_COLS = (
    ("OVERALL", "OVERALL"),
    ("header_field_accuracy", "header acc"),
    ("row_f1", "row F1"),
    ("documents_fully_correct", "docs fully correct"),
    ("false_fill_rate", "false-fill"),
)
DEFAULT_SWEEP_JSON = (
    paths.runs_dir() / "res_sweep" / "ressweep_ebf9661" / "ressweep_result.json"
)


def _script(name: str) -> ModuleType:
    """Import ``scripts/<name>.py`` (scripts are not a package); reuse an already loaded copy."""
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(
        name, Path(__file__).resolve().parent / f"{name}.py"
    )
    if spec is None or spec.loader is None:  # pragma: no cover - the file is next to this one
        raise ImportError(name)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod  # dataclasses resolve annotations via sys.modules
    spec.loader.exec_module(mod)
    return mod


rv1 = _script("replay_v1_check")
rde = _script("row_error_diagnosis")


def assert_cross_resolution(
    native: Mapping[str, Any] | None,
    base: Mapping[str, Any] | None,
    configs_dir: Path | None = None,
) -> None:
    """Raise ValueError unless the runs are the intended native-vs-1260 pair.

    Required: both manifests carry a config hash, the hashes DIFFER, ``max_pixels`` resolves to
    2196480 (native) and 1310720 (base), and model id + revision, seed and ``docs_sha`` agree. A
    pair that is not exactly this one is refused, so this cannot become a general bypass of
    ``runcompat.assert_same_resolution``.
    """
    n, b = native or {}, base or {}
    hn, hb = manifest_config_hash(n), manifest_config_hash(b)
    if hn is None or hb is None:
        raise ValueError("both manifests must carry a config hash")
    if hn == hb:
        raise ValueError(
            "the runs share one config hash: this script compares DIFFERENT resolutions"
        )
    got = (resolve_max_pixels(n, configs_dir), resolve_max_pixels(b, configs_dir))
    if got != (NATIVE_MAX_PIXELS, BASE_MAX_PIXELS):
        raise ValueError(
            f"expected max_pixels (native, base) = {(NATIVE_MAX_PIXELS, BASE_MAX_PIXELS)}, "
            f"got {got}"
        )
    for key in ("model", "seed", "docs_sha"):
        if n.get(key) != b.get(key):
            raise ValueError(f"manifests differ in {key!r}: not a resolution-only difference")


def slices_of(gold: Mapping[str, Any], meta: Sequence[Mapping[str, Any]]) -> dict[str, list[str]]:
    """Slice name -> doc ids: all, scanned / digital, invoice / waybill, multipage, split."""
    tag = {m["doc_id"]: m for m in meta}
    ids = list(gold)
    return {
        "all": ids,
        "scanned": [d for d in ids if tag[d]["scanned"]],
        "digital": [d for d in ids if not tag[d]["scanned"]],
        "invoice": [d for d in ids if gold[d]["doc_type"] == "invoice"],
        "waybill": [d for d in ids if gold[d]["doc_type"] == "waybill"],
        "multipage": [d for d in ids if tag[d]["multipage"]],
        "single-page": [d for d in ids if not tag[d]["multipage"]],
        "train": [d for d in ids if d.startswith("train_")],
        "dev": [d for d in ids if d.startswith("dev_")],
    }


def paired_slices(
    pa: Mapping[str, Any],
    pb: Mapping[str, Any],
    gold: Mapping[str, Any],
    slices: Mapping[str, Sequence[str]],
    n_boot: int,
) -> dict[str, dict[str, Any]]:
    """Per slice: n and the paired bootstrap (B - A) of every metric of `METRIC_COLS`."""
    out: dict[str, dict[str, Any]] = {}
    for name, ids in slices.items():
        g = {d: gold[d] for d in ids}
        res = ev.paired_bootstrap(
            {d: pa[d] for d in ids}, {d: pb[d] for d in ids}, g, n=n_boot, seed=SEED
        )
        out[name] = {"n": len(ids), **{k: res[k] for k, _ in METRIC_COLS}}
    return out


def misread_vector(
    pred: Mapping[str, Any],
    gold: Mapping[str, Any],
    traces: Mapping[str, Any],
    indexes: Mapping[str, Any],
    ids: Sequence[str],
    sc: ModuleType,
) -> list[int]:
    """Part-number misreads per doc (the 06 definition) for the docs `ids`."""
    return [
        ressweep.doc_spn_misreads(pred.get(d), gold[d], traces[d], indexes.get(d), sc, rde)
        for d in ids
    ]


def pts(x: float) -> str:
    """Fraction -> signed percentage points, two decimals."""
    return f"{100 * x:+.2f}"


def fmt_ci(r: Mapping[str, float]) -> str:
    """``+d [+lo, +hi]`` in points."""
    return f"{pts(r['delta'])} [{pts(r['lo'])}, {pts(r['hi'])}]"


def md_table(head: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    """Markdown table."""
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def slice_table(res: Mapping[str, Mapping[str, Any]], a_name: str, b_name: str) -> str:
    """Paired-delta table of every metric per slice (points; B - A)."""
    head = ["slice", "docs", *[f"{lab} d [CI]" for _, lab in METRIC_COLS]]
    rows = [[s, r["n"], *[fmt_ci(r[k]) for k, _ in METRIC_COLS]] for s, r in res.items()]
    return f"Paired deltas, {b_name} minus {a_name} (points, 95% CI):\n\n" + md_table(head, rows)


def level_table(res: Mapping[str, Any], a_name: str, b_name: str) -> str:
    """Levels of the 'all' slice of a paired result, A and B side by side."""
    rows = [
        [lab, f"{100 * res['all'][k]['a']:.2f}", f"{100 * res['all'][k]['b']:.2f}"]
        for k, lab in METRIC_COLS
    ]
    return md_table(["metric (all 500 docs, %)", a_name, b_name], rows)


def count_row(label: str, c: Mapping[str, float]) -> list[Any]:
    """One row of the misread table: before -> after and the paired CI of the difference."""
    return [
        label,
        f"{c['control']:.0f} -> {c['candidate']:.0f}",
        f"{c['delta']:+.0f} [{c['lo']:+.0f}, {c['hi']:+.0f}]",
    ]


def load_gold_500() -> dict[str, Any]:
    """Gold of the 500 train + dev docs."""
    gold: dict[str, Any] = {}
    for split in ("train", "dev"):
        gold |= ev.load_gold(paths.data_dir() / split / "labels")
    return gold


def analyse(
    native_dir: Path,
    base_dir: Path,
    ocr_cache: Path | None,
    n_boot: int = N_BOOT,
    sweep_json: Path | None = None,
) -> dict[str, Any]:
    """Every number of the report as one dict (aggregates only)."""
    man_n, man_b = read_manifest(native_dir), read_manifest(base_dir)
    assert_cross_resolution(man_n, man_b)
    sc = ev.load_scorer()
    gold = load_gold_500()
    pred = {
        "native": json.loads((native_dir / "predictions.json").read_text(encoding="utf-8")),
        "base": json.loads((base_dir / "predictions.json").read_text(encoding="utf-8")),
    }
    # gold order (train then dev), as in replay_v1_check: the paired bootstrap's resample indices
    # depend on document order, so this keeps every CI comparable with reports/v1_5_replay_native.md
    ids = list(gold)
    for k, p in pred.items():
        if sorted(d for d in p if d in gold) != sorted(ids):
            raise SystemExit(f"{k} run does not cover exactly the 500 train + dev docs")
    gold = {d: gold[d] for d in ids}
    pred = {k: {d: p[d] for d in ids} for k, p in pred.items()}
    traces = {
        "native": [t for t in read_trace(native_dir / "trace.jsonl") if t["doc_id"] in gold],
        "base": [t for t in read_trace(base_dir / "trace.jsonl") if t["doc_id"] in gold],
    }
    meta = ev.load_json(ROOT / "meta" / "train.json") + ev.load_json(ROOT / "meta" / "dev.json")
    sl = slices_of(gold, meta)
    ocr = ev.load_ocr_pages(ids, ocr_cache)
    if any(d not in ocr for d in ids):
        raise SystemExit("OCR cache incomplete for the 500 docs")
    indexes = {d: locate.build_index(ocr[d]) for d in ids}
    tr = {k: {t["doc_id"]: t for t in v} for k, v in traces.items()}
    mis = {k: misread_vector(pred[k], gold, tr[k], indexes, ids, sc) for k in pred}
    scanned_ix = [i for i, d in enumerate(ids) if d in set(sl["scanned"])]
    res: dict[str, Any] = {
        "n_docs": len(ids),
        "n_boot": n_boot,
        "native_run": native_dir.name,
        "base_run": base_dir.name,
        "native_hash": manifest_config_hash(man_n),
        "base_hash": manifest_config_hash(man_b),
        "native_code_sha": man_n.get("code_sha"),
        "base_code_sha": man_b.get("code_sha"),
        "native_batch": man_n.get("batch_size"),
        "base_batch": man_b.get("batch_size"),
        "raw": paired_slices(pred["base"], pred["native"], gold, sl, n_boot),
        "misreads": {
            "all": ressweep.paired_count_delta(mis["base"], mis["native"], n_boot),
            "scanned": ressweep.paired_count_delta(
                [mis["base"][i] for i in scanned_ix], [mis["native"][i] for i in scanned_ix], n_boot
            ),
        },
    }
    # Rules, production path, both runs. Honest per-fold R3 shapes and the frozen shipping shapes.
    doc_fold = {
        str(d): int(f)
        for d, f in json.loads((ROOT / "splits" / "folds.json").read_text("utf-8"))[
            "doc_fold"
        ].items()
    }
    groups = json.loads((ROOT / "meta" / "supplier_groups.json").read_text(encoding="utf-8"))
    labels = meta_mod.load_labels("train") + meta_mod.load_labels("dev")
    honest = rv1.fold_shape_fn(labels, doc_fold, groups)
    frozen, frozen_sha = load_slot_shapes()
    res["frozen_shapes_sha"] = frozen_sha
    res["rules"] = {}
    for name, shapes in (("honest", honest), ("shipping", frozen)):
        fin = {
            k: rv1.production(traces[k], RuleConfig(), shapes, ocr_cache)[0]
            for k in ("native", "base")
        }
        fin = {k: {d: v[d] for d in ids} for k, v in fin.items()}
        res["rules"][name] = {
            "native_rules_vs_native_raw": paired_slices(
                pred["native"], fin["native"], gold, sl, n_boot
            ),
            "native_rules_vs_base_rules": paired_slices(
                fin["base"], fin["native"], gold, sl, n_boot
            ),
        }
    # 40-document directional check against the 06 sweep.
    spike = json.loads((ROOT / "splits" / "spike40.json").read_text(encoding="utf-8"))
    sub = [d for d in spike if d in gold]
    if len(sub) != len(spike):
        raise SystemExit("spike40 docs are not all in the 500-doc runs")
    g40 = {d: gold[d] for d in sub}
    ix40 = [ids.index(d) for d in sub]
    res["spike40"] = {
        "n": len(sub),
        "scores": paired_slices(pred["base"], pred["native"], gold, {"spike40": sub}, n_boot)[
            "spike40"
        ],
        "misreads": ressweep.paired_count_delta(
            [mis["base"][i] for i in ix40], [mis["native"][i] for i in ix40], n_boot
        ),
        "base_overall": ev.score({d: pred["base"][d] for d in sub}, g40)["all"]["OVERALL"],
        "native_overall": ev.score({d: pred["native"][d] for d in sub}, g40)["all"]["OVERALL"],
    }
    sj = sweep_json or DEFAULT_SWEEP_JSON
    if sj.is_file():
        sweep = json.loads(sj.read_text(encoding="utf-8"))
        cand = next(c for c in sweep["candidates"] if c["max_pixels"] == NATIVE_MAX_PIXELS)
        res["sweep"] = {
            "overall": cand["scores"]["all"]["OVERALL"],
            "misreads": cand["misreads"],
            "misreads_scanned": cand["misreads_scanned"],
            "n": sweep["n_docs"],
        }
    return res


def render(res: Mapping[str, Any], command: str, state: str) -> str:
    """The aggregates-only markdown block (between the ``native500`` markers)."""
    n = res["n_docs"]
    w = [
        TITLE + "\n",
        f"**Provenance.** Native run `{res['native_run']}` (code sha `{res['native_code_sha']}`, "
        f"config hash `{res['native_hash']}`, batch size {res['native_batch']}, max_pixels "
        f"{NATIVE_MAX_PIXELS}) against the 1260-token run `{res['base_run']}` (code sha "
        f"`{res['base_code_sha']}`, config hash `{res['base_hash']}`, batch size "
        f"{res['base_batch']}, max_pixels {BASE_MAX_PIXELS}); same {n} train + dev documents, same "
        f"model revision and seed. Command: `{command}` (repo state `{state}`; paired bootstrap "
        f"{res['n_boot']} doc-level resamples, seed {SEED}; unmodified scorer via `shipdoc.eval`). "
        "Batch size differs between the two runs (8 and 4); both benches record byte-identical "
        "outputs across batch sizes, so this is treated as a resolution-only difference. "
        "**All numbers UNVERIFIED** until a verifier recomputes them. Aggregates and counts "
        "only.\n",
        "### Raw output, native vs 1260\n",
        level_table(res["raw"], "1260 raw", "native raw"),
        slice_table(res["raw"], "1260 raw", "native raw"),
        "Part-number misreads (`ressweep.doc_spn_misreads`, the 06 definition; gold rows placed on "
        "pages with the OCR cache), 1260 -> native, paired CI of the count difference:\n",
        md_table(
            ["docs", "misreads", "delta [CI]"],
            [
                count_row("all 500", res["misreads"]["all"]),
                count_row("scanned", res["misreads"]["scanned"]),
            ],
        ),  # fmt: skip
    ]
    s40 = res["spike40"]
    w.append("### Directional check on the 40 sweep documents\n")
    rows = [
        [
            "500-doc runs restricted to the 40 spike docs (batch 8 / 4)",
            f"{100 * s40['base_overall']:.2f} -> {100 * s40['native_overall']:.2f}",
            fmt_ci(s40["scores"]["OVERALL"]),
            f"{s40['misreads']['control']:.0f} -> {s40['misreads']['candidate']:.0f}",
        ]
    ]
    sw = res.get("sweep")
    if sw:
        o = sw["overall"]
        rows.append(
            [
                f"06 sweep, own runs at batch 1 (`ressweep_result.json`, {sw['n']} docs)",
                f"{100 * o['a']:.2f} -> {100 * o['b']:.2f}",
                fmt_ci(o),
                f"{sw['misreads']['control']:.0f} -> {sw['misreads']['candidate']:.0f}",
            ]
        )
    w.append(
        md_table(["source", "OVERALL 1260 -> native", "OVERALL d [CI] (pts)", "misreads"], rows)
    )
    variants = (
        ("honest", "HONEST (supplier-held-out R3 shapes)"),
        ("shipping", "SHIPPING (frozen `meta/slot_shapes.json`, in-sample)"),
    )
    for name, title in variants:
        r = res["rules"][name]
        w.append(f"### Rules at native, {title}\n")
        w.append(
            "Production path (`replay_v1_check.production`: R1 + R2 + R3, coerce / repair), both "
            f"runs; frozen shapes sha256 `{res['frozen_shapes_sha']}`.\n"
        )
        w.append("Native ZS + rules vs native raw.\n")
        w.append(slice_table(r["native_rules_vs_native_raw"], "native raw", "native ZS+rules"))
        w.append("Native ZS + rules (v1.5) vs the 1260 ZS + rules (v1), same shapes variant.\n")
        w.append(
            level_table(r["native_rules_vs_base_rules"], "1260 ZS+rules (v1)", "native ZS+rules")
        )
        w.append(
            slice_table(r["native_rules_vs_base_rules"], "1260 ZS+rules (v1)", "native ZS+rules")
        )
    return "\n".join(w)


def merge_block(text: str, block: str) -> str:
    """Replace the marked block of `text`, or append it (the text above is never altered)."""
    wrapped = f"{BEGIN}\n{block.rstrip()}\n{END}\n"
    if BEGIN in text and END in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END)
        return head + wrapped.rstrip("\n") + tail
    return text.rstrip("\n") + "\n\n" + wrapped


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--native-run", type=Path, required=True)
    ap.add_argument("--base-run", type=Path, required=True, help="the 1260-token 02 run")
    ap.add_argument("--ocr-cache", type=Path, default=None)
    ap.add_argument("--sweep-json", type=Path, default=None)
    ap.add_argument("--out", type=Path, default=ROOT / "reports" / "res_sweep.md")
    ap.add_argument("--n-boot", type=int, default=N_BOOT)
    a = ap.parse_args(argv)
    res = analyse(a.native_run, a.base_run, a.ocr_cache, a.n_boot, a.sweep_json)
    cmd = "uv run python scripts/native_confirm.py " + " ".join(
        argv if argv is not None else sys.argv[1:]
    )
    text = merge_block(a.out.read_text(encoding="utf-8"), render(res, cmd, rv1.git_state()))
    a.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
