"""G3: incremental ablation of the deterministic Phase 3 rules on saved model outputs (no model).

Input: the saved trace.jsonl of a run (raw model text per page). Every rung re-runs
parse -> merge -> normalize from ``raw_text`` with a set of rules switched on, scores the 100 dev
docs with the official scorer (unmodified, via `shipdoc.eval`) and compares rungs with the repo's
paired document-level bootstrap (`shipdoc.eval.paired_bootstrap`: 2000 resamples, seed 42).

R0 (the baseline G2) switches EVERYTHING below off, precisely:
  * merge: ``provenance_aware=False`` -> doc_type of the first parsed page, every header field =
    the first non-null value over the pages in page order ("any page"), no OCR total pointer;
    rows concatenated in page order; repeated column-header rows KEPT; all-null rows KEPT;
  * normalize: dates / numbers / codes switched off (values are only stripped and str()-ed, which
    the scorer ignores);
  * schema assembly is NOT a rule and stays on in every rung: only the 4 row keys are kept and a
    waybill has no line_items (schema), pages that failed to parse count as None.

Rungs, cumulative (each adds one rule to the previous): R1a dates (per-document resolution),
R1b + per-layout-cluster day/month order, R2 numbers, R2b code normalisation (currency upper-case,
airport city stripped), R5 provenance-aware merge, R6 OCR labelled-total page pointer, R7 repeated
header-row filter, R8 all-null-row drop. R3 (ISO 4217 / IATA) and R4 (AWB shape) are confidence-only
validators: they return flags and cannot change a value, so their OVERALL delta is 0 by
construction (asserted here and in tests/test_validate.py); they are reported by what their flags
catch. Synthetic sections are labelled SYNTHETIC and never mixed into the dev100 numbers.

Run: uv run python scripts/postproc_ablation.py [--run-dir DIR] [--out-dir DIR] [--write-report]
``--docs train+dev`` re-gates on a 500-doc run (the zero-shot run, unseen by construction): the
pages go through ``shipdoc.coerce.page_for_merge`` and every rung's output through
``coerce_doc`` + ``repair_doc`` exactly like the run's own writer, so R8 minus R6/R1b can be
compared with the run's ``predictions.json``; the section "G3 re-gate - Phase 3 post-processing
(500-doc zero-shot, train+dev)" goes between its own ``G3-500`` markers and the dev100 block is
never touched.
Writes <out-dir>/postproc_ablation.json (aggregates + value-level diffs) and, with
``--write-report``, the section "G3 - Phase 3 post-processing (dev100, final pick)" of
reports/ablations.md. All numbers are UNVERIFIED until a verifier recomputes them.
"""

# ruff: noqa: E501  # markdown table literals

from __future__ import annotations

import argparse
import copy
import json
import math
import random
import re
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

from _corpus import ROOT, load_corpus

from shipdoc import eval as ev
from shipdoc import ocr, paths
from shipdoc.cluster import LayoutClusters, layout_signature
from shipdoc.coerce import coerce_doc, page_for_merge, repair_doc
from shipdoc.extract import parse_output
from shipdoc.merge import FieldProvenance, merge_pages
from shipdoc.normalize import infer_date_order, normalize_date, normalize_doc, normalize_number
from shipdoc.replay import read_trace
from shipdoc.totals import pick_total
from shipdoc.validate import validate_doc, validate_value

DEFAULT_RUN = "spike_download2/x/dev100_qwen35_4b_img_only_2abf481"
SECTION = "G3 - Phase 3 post-processing (dev100, final pick)"
BEGIN, END = "<!-- G3-begin (generated by scripts/postproc_ablation.py) -->", "<!-- G3-end -->"
BEGIN_500 = "<!-- G3-500-begin (generated by scripts/postproc_ablation.py --docs train+dev) -->"
END_500 = "<!-- G3-500-end -->"
SECTION_500 = "G3 re-gate - Phase 3 post-processing (500-doc zero-shot, train+dev)"
N_BOOT, SEED = 2000, 42


def markers_500(tag: str = "") -> tuple[str, str]:
    """(begin, end) markers of the 500-doc block; `tag` selects a separate block (e.g. native)."""
    if not tag:
        return BEGIN_500, END_500
    slug = re.sub(r"[^a-z0-9]+", "-", tag.lower()).strip("-")
    return (
        f"<!-- G3-500-{slug}-begin (generated by scripts/postproc_ablation.py --docs train+dev "
        f"--report-tag) -->",
        f"<!-- G3-500-{slug}-end -->",
    )


@dataclass(frozen=True)
class Rules:
    """Which Phase 3 rules are on. The all-False value is R0."""

    dates: bool = False  # R1a
    cluster_dates: bool = False  # R1b
    numbers: bool = False  # R2
    codes: bool = False  # R2b
    provenance: bool = False  # R5
    total_ocr: bool = False  # R6
    header_rows: bool = False  # R7
    null_rows: bool = False  # R8


# (rung id, label, field switched on at that rung)
STEPS: list[tuple[str, str, str]] = [
    ("R1a", "dates -> ISO, per-document resolution", "dates"),
    ("R1b", "+ per-layout-cluster day/month order", "cluster_dates"),
    ("R2", "number normalisation", "numbers"),
    ("R2b", "code normalisation (currency case, airport city strip)", "codes"),
    ("R5", "provenance-aware merge (page-1 identity, last-page totals)", "provenance"),
    ("R6", "OCR labelled-total page pointer", "total_ocr"),
    ("R7", "repeated header-row filter", "header_rows"),
    ("R8", "drop all-null rows", "null_rows"),
]
FULL = Rules(**{f: True for _, _, f in STEPS})


# ------------------------------------------------------------------------------ pipeline


class Ctx:
    """Everything a rung needs besides its Rules: parsed pages, OCR totals, cluster date orders."""

    def __init__(self, traces: list[dict[str, Any]], finalize: bool = False) -> None:
        self.prov = FieldProvenance.load()
        # finalize = the run writer's path: number token text kept through the merge, and every
        # output coerced to plain-number strings + schema-invalid dates nulled (shipdoc.coerce).
        self.finalize = finalize
        self.pages = {t["doc_id"]: [self._page(p["raw_text"]) for p in t["pages"]] for t in traces}
        self.date_order: dict[str, str | None] = {}  # set once the layout clusters are fit
        self.total_page: dict[str, int | None] = {}
        self.total_value: dict[str, str | None] = {}
        for t in traces:
            cand = pick_total(ocr.doc_pages(t["doc_id"]))
            self.total_page[t["doc_id"]] = None if cand is None else cand.page
            self.total_value[t["doc_id"]] = None if cand is None else cand.value

    def _page(self, raw: str) -> dict[str, Any] | None:
        """One page as the merge receives it (token-text numbers when finalizing)."""
        parsed = parse_output(raw, "json")
        return page_for_merge(raw, parsed, "json") if self.finalize else parsed


def run_doc(doc_id: str, rules: Rules, ctx: Ctx) -> tuple[dict[str, Any], dict[str, list[str]]]:
    """parse -> merge -> normalize of one doc under `rules`; returns (doc, normalize flags)."""
    page = ctx.total_page[doc_id] if rules.total_ocr else None
    hints = {"total_amount": page} if page is not None else None
    merged = merge_pages(
        ctx.pages[doc_id],
        ctx.prov,
        drop_null_rows=rules.null_rows,
        provenance_aware=rules.provenance,
        drop_header_rows=rules.header_rows,
        total_page_hints=hints,
    )
    order = ctx.date_order.get(doc_id) if rules.cluster_dates else None
    doc, flags = normalize_doc(
        merged.doc,
        dates=rules.dates,
        numbers=rules.numbers,
        codes=rules.codes,
        date_order=order,
    )
    if ctx.finalize:
        doc = repair_doc(coerce_doc(doc))[0]
    return doc, flags


def run_all(rules: Rules, ctx: Ctx) -> dict[str, Any]:
    """Predictions of every doc under `rules`."""
    return {d: run_doc(d, rules, ctx)[0] for d in ctx.pages}


def raw_dates(ctx: Ctx) -> dict[str, str | None]:
    """Merged raw ``invoice_date`` per doc (before normalisation), the input of R1."""
    out: dict[str, str | None] = {}
    for d, pages in ctx.pages.items():
        v = merge_pages(pages, ctx.prov).doc["header"].get("invoice_date")
        out[d] = None if v is None else str(v).strip() or None
    return out


# ------------------------------------------------------------------------------ statistics


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson 95% interval of a proportion (0/0 -> (nan, nan))."""
    if n == 0:
        return math.nan, math.nan
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return c - h, c + h


def paired(pa: dict[str, Any], pb: dict[str, Any], gold: dict[str, Any]) -> dict[str, Any]:
    """Paired bootstrap of B - A on OVERALL (+ false-fill). Identical predictions: exact zeros
    (every resample gives the same score for both systems, so the percentile CI is [0, 0])."""
    if pa == pb:
        z = {"delta": 0.0, "lo": 0.0, "hi": 0.0}
        return {"OVERALL": z, "false_fill_rate": dict(z), "identical": True}
    r = ev.paired_bootstrap(pa, pb, gold, n=N_BOOT, seed=SEED)
    keep = ("delta", "lo", "hi")
    return {
        "OVERALL": {k: r["OVERALL"][k] for k in keep},
        "false_fill_rate": {k: r["false_fill_rate"][k] for k in keep},
        "identical": False,
    }


def excludes_0(d: dict[str, float]) -> bool:
    return d["lo"] > 0 or d["hi"] < 0


def cell_changes(pa: dict[str, Any], pb: dict[str, Any]) -> dict[str, int]:
    """Cells that differ between two prediction sets: ``header.<f>`` counts and ``rows`` /
    ``row_cells`` (rows added/removed, row fields edited). Counts only."""
    c: Counter[str] = Counter()
    for d, a in pa.items():
        b = pb[d]
        for k in set(a["header"]) | set(b["header"]):
            if a["header"].get(k) != b["header"].get(k):
                c[f"header.{k}"] += 1
        c["rows"] += abs(len(a["line_items"]) - len(b["line_items"]))
        if len(a["line_items"]) == len(b["line_items"]):
            for ra, rb in zip(a["line_items"], b["line_items"], strict=True):
                c["row_cells"] += sum(ra.get(k) != rb.get(k) for k in set(ra) | set(rb))
    return {k: v for k, v in c.items() if v}


def header_flips(
    pa: dict[str, Any], pb: dict[str, Any], gold: dict[str, Any]
) -> dict[str, dict[str, int]]:
    """Per header field: docs that went wrong->right (``gain``) and right->wrong (``loss``)."""
    ra, rb = ev.per_doc_results(pa, gold), ev.per_doc_results(pb, gold)
    out: dict[str, dict[str, int]] = defaultdict(lambda: {"gain": 0, "loss": 0})
    for d in gold:
        for k, ok_a in ra[d]["header"].items():
            ok_b = rb[d]["header"][k]
            if ok_b and not ok_a:
                out[k]["gain"] += 1
            elif ok_a and not ok_b:
                out[k]["loss"] += 1
    return dict(out)


def row_effect(pa: dict[str, Any], pb: dict[str, Any], gold: dict[str, Any]) -> dict[str, int]:
    """Change in correct rows / predicted rows (totals over the docs)."""
    ra, rb = ev.per_doc_results(pa, gold), ev.per_doc_results(pb, gold)
    return {
        "rows_full": sum(rb[d]["rows_full"] - ra[d]["rows_full"] for d in gold),
        "rows_pred": sum(rb[d]["rows_pred"] - ra[d]["rows_pred"] for d in gold),
    }


def point(pred: dict[str, Any], gold: dict[str, Any]) -> dict[str, Any]:
    """Aggregate metrics + 95% CIs of OVERALL / false-fill of one prediction set."""
    agg = ev.score(pred, gold)["all"]
    per = list(ev.per_doc_results(pred, gold).values())
    ci = ev.bootstrap_metrics(per, n=N_BOOT, seed=SEED)
    return {
        "OVERALL": agg["OVERALL"],
        "OVERALL_ci": [ci["OVERALL"]["lo"], ci["OVERALL"]["hi"]],
        "header": agg["header_field_accuracy"],
        "row_f1": agg["row_f1"],
        "fully_correct": agg["documents_fully_correct"],
        "false_fill": agg["false_fill_rate"],
        "false_fill_ci": [ci["false_fill_rate"]["lo"], ci["false_fill_rate"]["hi"]],
        "header_by_field": agg["header_by_field"],
    }


# ------------------------------------------------------------------------------ ladder


def ladder(ctx: Ctx, gold: dict[str, Any]) -> dict[str, Any]:
    """Cumulative ladder, leave-one-out and per-field effects."""
    preds: dict[str, dict[str, Any]] = {}
    rules = Rules()
    preds["R0"] = run_all(rules, ctx)
    rungs = [{"id": "R0", "label": "baseline G2 (everything off)", "rules": rules}]
    for rid, label, fld in STEPS:
        rules = replace(rules, **{fld: True})
        preds[rid] = run_all(rules, ctx)
        rungs.append({"id": rid, "label": label, "rules": rules})
    out_rungs: list[dict[str, Any]] = []
    for i, r in enumerate(rungs):
        rid = r["id"]
        row: dict[str, Any] = {"id": rid, "label": r["label"], **point(preds[rid], gold)}
        if i:
            prev = rungs[i - 1]["id"]
            row["vs_prev"] = paired(preds[prev], preds[rid], gold)
            row["vs_R0"] = paired(preds["R0"], preds[rid], gold)
            row["changes_vs_prev"] = cell_changes(preds[prev], preds[rid])
            row["header_flips_vs_prev"] = header_flips(preds[prev], preds[rid], gold)
            row["row_effect_vs_prev"] = row_effect(preds[prev], preds[rid], gold)
        out_rungs.append(row)
    loo = []
    full_pred = preds["R8"]
    for rid, label, fld in STEPS:
        pred = run_all(replace(FULL, **{fld: False}), ctx)
        loo.append(
            {
                "id": rid,
                "label": label,
                "OVERALL_without": ev.score(pred, gold)["all"]["OVERALL"],
                "full_minus_without": paired(pred, full_pred, gold),
                "changes": cell_changes(pred, full_pred),
                "header_flips": header_flips(pred, full_pred, gold),
            }
        )
    return {"rungs": out_rungs, "loo": loo, "preds": preds}


# ------------------------------------------------------------------------------ R3 / R4


def validator_report(
    pred: dict[str, Any], gold: dict[str, Any], corpus_gold: list[dict[str, Any]]
) -> dict[str, Any]:
    """What the confidence-only flags catch on the dev100 predictions, and their false-alarm rate
    on the gold values of all train+dev docs. Also asserts they never change a value."""
    sc = ev.load_scorer()
    before = json.dumps(pred, sort_keys=True)
    groups = {
        "R3 currency (ISO 4217)": ("currency",),
        "R3 airports (IATA)": ("origin_airport", "destination_airport"),
        "R4 AWB shape (awb_number, mawb)": ("awb_number", "mawb"),
        "R4 HAWB shape": ("hawb",),
    }
    rows: dict[str, Counter[str]] = {g: Counter() for g in groups}
    for d, g in gold.items():
        flags = validate_doc(pred[d])
        for gname, fields in groups.items():
            for f in fields:
                v = pred[d]["header"].get(f)
                if v is None or not str(v).strip():
                    continue
                wrong = not sc.same(f, v, g["header"].get(f))
                flagged = f"header.{f}" in flags
                c = rows[gname]
                c["n"] += 1
                c["wrong"] += wrong
                c["flagged"] += flagged
                c["flagged_wrong"] += flagged and wrong
                c["flagged_right"] += flagged and not wrong
    assert json.dumps(pred, sort_keys=True) == before, "validators changed a prediction"
    out: dict[str, Any] = {}
    for gname, c in rows.items():
        n, w, fl, fw = c["n"], c["wrong"], c["flagged"], c["flagged_wrong"]
        out[gname] = {
            **dict(c),
            "base_error_rate": w / n if n else None,
            "recall_of_errors": fw / w if w else None,
            "flag_precision": fw / fl if fl else None,
            "false_alarm_rate": c["flagged_right"] / (n - w) if n - w else None,
            "false_alarm_wilson": wilson(c["flagged_right"], n - w),
        }
    # False alarms on GOLD values of all 500 train+dev docs (large n; every gold value is correct).
    ga: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for g in corpus_gold:
        for f, v in g["header"].items():
            if v is None or not str(v).strip():
                continue
            fl = validate_value(f, v)
            for gname, fields in groups.items():
                if f in fields:
                    ga[gname][0] += 1
                    ga[gname][1] += bool(fl)
    out["gold_false_alarms_train_dev"] = {k: {"n": a, "flagged": b} for k, (a, b) in ga.items()}
    return out


_LOOKALIKE = {"0": "O", "1": "I", "5": "S", "8": "B", "2": "Z", "6": "G", "O": "0", "I": "1"}
_LOOKALIKE.update({"S": "5", "B": "8", "Z": "2", "G": "6"})


def _mutate(value: str, kind: str, rng: random.Random) -> str | None:
    """One synthetic reading error of `kind`; None if not applicable to this value."""
    pos = [i for i, ch in enumerate(value) if ch.isalnum()]
    if not pos:
        return None
    i = rng.choice(pos)
    ch = value[i]
    pool = "0123456789" if ch.isdigit() else "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    if kind == "look_alike":
        cand = [j for j in pos if value[j].upper() in _LOOKALIKE]
        if not cand:
            return None
        j = rng.choice(cand)
        return value[:j] + _LOOKALIKE[value[j].upper()] + value[j + 1 :]
    if kind == "same_class_substitution":
        new = rng.choice([c for c in pool if c != ch.upper()])
        return value[:i] + (new.lower() if ch.islower() else new) + value[i + 1 :]
    if kind == "drop_char":
        return value[:i] + value[i + 1 :]
    if kind == "insert_char":
        return value[:i] + rng.choice(pool) + value[i:]
    if kind == "swap_adjacent":
        j = i + 1
        if j >= len(value) or not value[j].isalnum() or value[j] == ch:
            return None
        return value[:i] + value[j] + ch + value[j + 2 :]
    raise ValueError(kind)


def validator_injection(corpus_gold: list[dict[str, Any]]) -> dict[str, Any]:
    """SYNTHETIC: catch rate of each flag on gold values with one injected reading error."""
    rng = random.Random(SEED)
    groups = {
        "currency": ("currency",),
        "airport": ("origin_airport", "destination_airport"),
        "awb": ("awb_number", "mawb"),
        "hawb": ("hawb",),
    }
    kinds = ("look_alike", "same_class_substitution", "drop_char", "insert_char", "swap_adjacent")
    res: dict[str, dict[str, list[int]]] = {g: {k: [0, 0] for k in kinds} for g in groups}
    for g in corpus_gold:
        for f, v in g["header"].items():
            for gname, fields in groups.items():
                if f not in fields or v is None or not str(v).strip():
                    continue
                for k in kinds:
                    m = _mutate(str(v), k, rng)
                    if m is None or m == str(v):
                        continue
                    res[gname][k][0] += 1
                    res[gname][k][1] += bool(validate_value(f, m))
    return {g: {k: {"n": a, "flagged": b} for k, (a, b) in d.items()} for g, d in res.items()}


# ------------------------------------------------------------------------------ R1 / R2 synthetic

#: Printed date format per invoice supplier group (reports/recon.md section 4, from page images).
GROUP_DATE_FORMAT = {
    "inv_g01": "mdy/", "inv_g02": "Month D, Y", "inv_g03": "Month D, Y", "inv_g04": "D-MON-Y",
    "inv_g05": "D-MON-Y", "inv_g06": "Month D, Y", "inv_g07": "dmy/", "inv_g08": "D-MON-Y",
    "inv_g09": "mdy/", "inv_g10": "mdy/", "inv_g11": "iso", "inv_g12": "dmy/",
    "inv_g13": "iso", "inv_g14": "D-MON-Y", "inv_g15": "dmy/", "inv_g16": "D-MON-Y",
    "inv_g17": "Month D, Y", "inv_g18": "mdy/",
}  # fmt: skip
_MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
_MONTH = [
    "January", "February", "March", "April", "May", "June", "July", "August", "September",
    "October", "November", "December",
]  # fmt: skip


def render_date(iso: str, fmt: str) -> str:
    """Gold ISO date printed in `fmt` (synthetic raw variant)."""
    y, m, d = (int(x) for x in iso.split("-"))
    return {
        "iso": iso,
        "dmy/": f"{d:02d}/{m:02d}/{y}",
        "mdy/": f"{m:02d}/{d:02d}/{y}",
        "D-MON-Y": f"{d:02d}-{_MON[m - 1].upper()}-{y}",
        "Month D, Y": f"{_MONTH[m - 1]} {d}, {y}",
    }[fmt]


def date_synthetic(corp: list[Any], cluster_of: dict[str, int]) -> dict[str, Any]:
    """SYNTHETIC: gold dates re-printed in raw formats, normalised per document vs per cluster.

    Scenario `seen_formats`: each group prints its own recon format. Scenario `numeric_stress`:
    every group prints a numeric date (groups alternate DD/MM and MM/DD), so day<=12 dates (22.7%
    of all gold dates) are genuinely ambiguous per document. Cluster pools use the predicted
    (label-free) clusters and, for comparison, the oracle supplier group. Reports counts of
    correct / unresolved (left raw, flagged) / wrong (a different ISO date).
    """
    invs = [r for r in corp if r.doc_type == "invoice" and r.gold["header"].get("invoice_date")]
    groups = sorted({r.group for r in invs})
    numeric_fmt = {g: ("dmy/" if i % 2 else "mdy/") for i, g in enumerate(groups)}
    out: dict[str, Any] = {"n_dates": len(invs)}
    for scen in ("seen_formats", "numeric_stress"):
        fmt_of = {
            r.doc_id: (
                GROUP_DATE_FORMAT[r.group] if scen == "seen_formats" else numeric_fmt[r.group]
            )
            for r in invs
        }
        raw = {
            r.doc_id: render_date(r.gold["header"]["invoice_date"], fmt_of[r.doc_id]) for r in invs
        }
        res: dict[str, Any] = {}
        for mode in ("raw_untouched", "per_document", "predicted_cluster", "oracle_group"):
            pools: dict[Any, list[str]] = defaultdict(list)
            for r in invs:
                key = cluster_of[r.doc_id] if mode == "predicted_cluster" else r.group
                pools[key].append(raw[r.doc_id])
            orders = {k: infer_date_order(v) for k, v in pools.items()}
            c = Counter()
            for r in invs:
                gold_iso = r.gold["header"]["invoice_date"]
                if mode == "raw_untouched":
                    got = raw[r.doc_id]
                else:
                    key = cluster_of[r.doc_id] if mode == "predicted_cluster" else r.group
                    order = orders[key] if mode != "per_document" else None
                    got, _ = normalize_date(raw[r.doc_id], order)
                c[
                    "correct"
                    if got == gold_iso
                    else "unresolved"
                    if got == raw[r.doc_id]
                    else "wrong"
                ] += 1
            res[mode] = dict(c)
            if mode != "per_document":
                res[mode]["pools_with_inferred_order"] = sum(o is not None for o in orders.values())
                res[mode]["pools"] = len(orders)
        out[scen] = res
    return out


def number_synthetic(gold: dict[str, Any]) -> dict[str, Any]:
    """SYNTHETIC: gold totals (2 decimals) and the first 3 quantities per doc (integers)
    re-printed with separators / symbols, scored by the official `same` untouched and after
    `normalize_number`. ``digits_altered`` counts outputs whose digit sequence differs from the
    printed one (must be 0: the normaliser may only re-format). Counts only."""
    sc = ev.load_scorer()

    def variants(x: float, two_dp: bool) -> dict[str, str]:
        s = f"{x:,.2f}" if two_dp else f"{x:,.0f}"
        eu = s.replace(",", "_").replace(".", ",").replace("_", ".")
        return {
            "comma_thousands": s,
            "code_prefix": f"USD {s}",
            "symbol_prefix": f"${s}",
            "decimal_comma": eu,
            "space_thousands": s.replace(",", " ").replace(".", ",")
            if two_dp
            else s.replace(",", " "),
            "decimal_comma_code_suffix": f"{eu} EUR",
        }

    items: list[tuple[str, str, bool]] = []
    for g in gold.values():
        if g["doc_type"] == "invoice" and g["header"].get("total_amount") is not None:
            items.append(("total_amount", str(g["header"]["total_amount"]), True))
        for r in g["line_items"][:3]:
            if r.get("quantity") is not None:
                items.append(("quantity", str(r["quantity"]), False))
    res: dict[str, Counter[str]] = defaultdict(Counter)
    for f, gv, two_dp in items:
        for name, s in variants(float(gv), two_dp).items():
            norm, _ = normalize_number(s)
            c = res[f"{f} / {name}"]
            c["n"] += 1
            c["raw_correct"] += sc.same(f, s, gv)
            c["normalized_correct"] += sc.same(f, norm, gv)
            c["digits_altered"] += re.sub(r"\D", "", norm) != re.sub(r"\D", "", s)
    return {k: dict(v) for k, v in sorted(res.items())}


# ------------------------------------------------------------------------------ R6 side stat


def total_pointer_stats(ctx: Ctx, gold: dict[str, Any], pred: dict[str, Any]) -> dict[str, Any]:
    """OCR labelled-total vs the VLM total: how often the pointer exists / agrees (counts)."""
    sc = ev.load_scorer()
    c: Counter[str] = Counter()
    for d, g in gold.items():
        if g["doc_type"] != "invoice":
            continue
        c["invoices"] += 1
        ocr_v = ctx.total_value[d]
        if ctx.total_page[d] is None:
            c["no_label_found"] += 1
            continue
        c["label_found"] += 1
        multipage = len(ctx.pages[d]) > 1
        c["label_on_last_page"] += ctx.total_page[d] == len(ctx.pages[d]) - 1
        c["multipage"] += multipage
        vlm_ok = sc.same(
            "total_amount", pred[d]["header"].get("total_amount"), g["header"]["total_amount"]
        )
        c["vlm_total_correct"] += vlm_ok
        if ocr_v is not None:
            agree = sc.same("total_amount", pred[d]["header"].get("total_amount"), ocr_v)
            c["ocr_value_parsed"] += 1
            c["agree"] += agree
            c["agree_and_vlm_correct"] += agree and vlm_ok
            c["disagree_and_vlm_correct"] += (not agree) and vlm_ok
    return dict(c)


# ------------------------------------------------------------------------------ report


def pct(x: float) -> str:
    return f"{100 * x:.2f}"


def ci_str(lo: float, hi: float) -> str:
    return f"[{100 * lo:+.2f}, {100 * hi:+.2f}]"


def kept_decision(rid: str, step: dict[str, Any]) -> str:
    """G3 gate per rung: CI of dOVERALL vs previous excludes 0, or false-fill drops with OVERALL
    not lower."""
    d = step["vs_prev"]
    if excludes_0(d["OVERALL"]):
        return (
            "KEEP (CI excludes 0)"
            if d["OVERALL"]["delta"] > 0
            else "DROP (CI excludes 0, negative)"
        )
    ff, ov = d["false_fill_rate"]["delta"], d["OVERALL"]["delta"]
    if ff < 0 and ov >= 0:
        return "KEEP (false-fill lower, OVERALL not lower)"
    return "FAIL gate (no measured effect)" if ov == 0 and ff == 0 else "FAIL gate (CI includes 0)"


def build_markdown(res: dict[str, Any], meta: dict[str, Any]) -> str:
    """The G3 section (aggregates only; no gold or predicted values)."""
    L: list[str] = []
    rungs = res["ladder"]["rungs"]
    L.append(f"## {SECTION}")
    L.append("")
    L.append(
        f"**Every number below is UNVERIFIED** (produced by `uv run python scripts/postproc_ablation.py --write-report`; "
        f"input `{meta['run']}` at code {meta['code']}; n = {meta['n_docs']} dev docs; paired document-level bootstrap, "
        f"{N_BOOT} resamples, seed {SEED}, `shipdoc.eval.paired_bootstrap`; scorer unmodified). Deltas are in OVERALL points (x100)."
    )
    L.append("")
    L.append(
        "**Caveat (read first).** Only the 100 dev docs of seen layouts exist for the final pick (image-only, keyed format, Qwen3.5-4B). "
        "Spec section 5 asks for G3 on 500-doc OOF; the zero-shot 500-doc run (Step U, not yet run) will re-measure this ladder. "
        f"100 docs give a 95% OVERALL interval of [{pct(rungs[0]['OVERALL_ci'][0])}, {pct(rungs[0]['OVERALL_ci'][1])}] for R0, so a rule with a small true effect cannot be detected here. "
        "A rule with delta exactly 0 and zero changed values is reported as such: the model already emits clean values on this run, "
        "so no benefit is claimed for it. Sections marked SYNTHETIC test that a rule's mechanism works on constructed raw variants; "
        "they are not measured benefits on model output."
    )
    L.append("")
    L.append("### R0 definition (what is switched off)")
    L.append("")
    L.append(
        "R0 = the baseline G2: raw model output, minimal merge. doc_type of the first parsed page; every header field is the first "
        'non-null value over the pages in page order ("any page"); rows concatenated in page order with repeated column-header '
        "rows and all-null rows KEPT; no normalisation (values only stripped / str()-ed, which the scorer ignores); no OCR. "
        "Not a rule, on in every rung: only the 4 row keys are kept, a waybill has no line_items, a page that failed to parse is None "
        f"({meta['parse_failures']} failed pages in this run). Rungs add one rule each, cumulatively, in the order below; "
        "R3/R4 are confidence-only and are not rungs."
    )
    L.append("")
    L.append("### (a) Cumulative ladder")
    L.append("")
    L.append(
        "| step | rule | OVERALL [95% CI] | false-fill rate [95% CI] | d vs previous [CI] | d vs R0 [CI] | values changed vs previous | G3 verdict |"
    )
    L.append("|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(rungs):
        ci = f"{pct(r['OVERALL'])} [{pct(r['OVERALL_ci'][0])}, {pct(r['OVERALL_ci'][1])}]"
        ff = f"{pct(r['false_fill'])} [{pct(r['false_fill_ci'][0])}, {pct(r['false_fill_ci'][1])}]"
        if i == 0:
            L.append(f"| R0 | {r['label']} | {ci} | {ff} | - | - | - | - |")
            continue
        p, z = r["vs_prev"]["OVERALL"], r["vs_R0"]["OVERALL"]
        ch = r["changes_vs_prev"]
        chs = ", ".join(f"{k}:{v}" for k, v in sorted(ch.items())) or "none"
        L.append(
            f"| {r['id']} | {r['label']} | {ci} | {ff} | {100 * p['delta']:+.2f} {ci_str(p['lo'], p['hi'])} | "
            f"{100 * z['delta']:+.2f} {ci_str(z['lo'], z['hi'])} | {chs} | {kept_decision(r['id'], r)} |"
        )
    L.append(
        "| R3 | ISO 4217 / IATA validation (confidence only) | = R8 | = R8 | 0 by construction (asserted) | 0 | none (flags only) | see (d) |"
    )
    L.append(
        "| R4 | AWB / HAWB shape (confidence only) | = R8 | = R8 | 0 by construction (asserted) | 0 | none (flags only) | see (d) |"
    )
    L.append("")
    L.append(
        f"Check: the R8 rung (R1b and R6 aside) reproduces the saved predictions of the run "
        f"(`predictions.json`): {meta['repro']}."
    )
    L.append("")
    L.append("### (b) Leave-one-out (full pipeline minus one rule)")
    L.append("")
    L.append(
        "| rule | OVERALL without | d (full - without) [CI] | values changed | CI excludes 0 |"
    )
    L.append("|---|---|---|---|---|")
    for r in res["ladder"]["loo"]:
        d = r["full_minus_without"]["OVERALL"]
        chs = ", ".join(f"{k}:{v}" for k, v in sorted(r["changes"].items())) or "none"
        L.append(
            f"| {r['id']} {r['label']} | {pct(r['OVERALL_without'])} | {100 * d['delta']:+.2f} {ci_str(d['lo'], d['hi'])} | {chs} | {'yes' if excludes_0(d) else 'no'} |"
        )
    L.append("")
    L.append(
        "### (c) Per-field effects (docs whose field went wrong->right / right->wrong, vs previous rung)"
    )
    L.append("")
    L.append("| step | header fields | row effect (correct rows / predicted rows) |")
    L.append("|---|---|---|")
    for r in rungs[1:]:
        fl = (
            ", ".join(
                f"{k}: +{v['gain']}/-{v['loss']}"
                for k, v in sorted(r["header_flips_vs_prev"].items())
            )
            or "no field changed"
        )
        re_ = r["row_effect_vs_prev"]
        L.append(f"| {r['id']} | {fl} | {re_['rows_full']:+d} / {re_['rows_pred']:+d} |")
    L.append("")
    r0, rf = rungs[0], rungs[-1]
    L.append("Header accuracy by field, R0 -> R8:")
    L.append("")
    L.append("| field | R0 | R8 |")
    L.append("|---|---|---|")
    for k in sorted(rf["header_by_field"]):
        a, b = r0["header_by_field"][k], rf["header_by_field"][k]
        L.append(f"| {k} | {pct(a)} | {pct(b)} |")
    L.append("")
    L.append("### (d) Confidence-only rules R3 / R4 (dev100 predictions of the R8 rung)")
    L.append("")
    L.append(
        "Flags cannot change a value (`validate_doc` returns flags only; this script asserts the prediction is byte-identical before and after, "
        "`tests/test_validate.py` asserts it on synthetic docs). Criterion for KEEP as a confidence feature: on real dev errors, "
        "n_wrong >= 5, recall of errors >= 50% and flag precision >= 2x the base error rate; with fewer than 5 real errors the flag is "
        "NOT ASSESSABLE on real data and the decision rests on the SYNTHETIC injection table plus the gold false-alarm count."
    )
    L.append("")
    L.append(
        "| flag | values | wrong | base error rate | flagged | flagged & wrong | recall of errors | flag precision | false-alarm rate (flagged / correct) [Wilson 95%] |"
    )
    L.append("|---|---|---|---|---|---|---|---|---|")
    for g, v in res["validators"].items():
        if g == "gold_false_alarms_train_dev":
            continue
        f = lambda x: "n/a" if x is None else f"{100 * x:.1f}%"  # noqa: E731
        lo, hi = v["false_alarm_wilson"]
        L.append(
            f"| {g} | {v['n']} | {v['wrong']} | {f(v['base_error_rate'])} | {v['flagged']} | {v['flagged_wrong']} | {f(v['recall_of_errors'])} | {f(v['flag_precision'])} | "
            f"{v['flagged_right']}/{v['n'] - v['wrong']} = {f(v['false_alarm_rate'])} [{100 * lo:.1f}, {100 * hi:.1f}] |"
        )
    L.append("")
    L.append(
        "False alarms on the GOLD values of all 500 train+dev docs (every gold value is correct, so every flag is a false alarm):"
    )
    L.append("")
    L.append("| flag | gold values | flagged | false-alarm rate |")
    L.append("|---|---|---|---|")
    for g, v in res["validators"]["gold_false_alarms_train_dev"].items():
        L.append(f"| {g} | {v['n']} | {v['flagged']} | {100 * v['flagged'] / v['n']:.2f}% |")
    L.append("")
    L.append(
        "SYNTHETIC injection (one reading error injected into each gold value of train+dev, seed 42): share of mutated values that the flag catches. Mechanism check only; real misreads are rarer and different."
    )
    L.append("")
    kinds = ["look_alike", "same_class_substitution", "drop_char", "insert_char", "swap_adjacent"]
    L.append("| flag | " + " | ".join(kinds) + " |")
    L.append("|---|" + "---|" * len(kinds))
    for g, d in res["injection"].items():
        cells = []
        for k in kinds:
            n, fl = d[k]["n"], d[k]["flagged"]
            cells.append(f"{100 * fl / n:.0f}% ({fl}/{n})" if n else "n/a")
        L.append(f"| {g} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("### R1 detail: does per-cluster inference add anything over per-document resolution?")
    L.append("")
    cl = res["clusters"]
    L.append(
        f"Layout clusters (OCR keyword+position signature of page 1, KMeans seed 42, k={cl['k']} chosen by silhouette {cl['silhouette']:.3f} "
        f"over k=8..30, fit on {cl['n_fit']} train+dev invoice pages, no labels, no test). Diagnostic only: ARI vs supplier group {cl['ari']:.3f}, "
        f"purity {cl['purity']:.3f}. On the dev100 run the model emitted dates as ISO in {meta['date_iso']}/{meta['date_total']} cases, so R1a/R1b receive no ambiguous input and change "
        f"{rungs[1]['changes_vs_prev'].get('header.invoice_date', 0)} / {rungs[2]['changes_vs_prev'].get('header.invoice_date', 0)} values."
    )
    L.append("")
    L.append(
        "SYNTHETIC raw variants (all 384 train+dev gold dates re-printed; counts of correct / left raw & flagged / wrong ISO):"
    )
    L.append("")
    L.append("| scenario | mode | correct | unresolved | wrong | pools with an inferred order |")
    L.append("|---|---|---|---|---|---|")
    for scen in ("seen_formats", "numeric_stress"):
        for mode, v in res["date_synthetic"][scen].items():
            pw = f"{v['pools_with_inferred_order']}/{v['pools']}" if "pools" in v else "-"
            L.append(
                f"| {scen} | {mode} | {v.get('correct', 0)} | {v.get('unresolved', 0)} | {v.get('wrong', 0)} | {pw} |"
            )
    L.append("")
    L.append(
        "Reading: on the five seen formats per-document resolution already resolves every date, so the cluster step adds nothing there "
        "(recon section 4: numeric-format groups have 0 gold dates with day <= 12). It only matters for an unseen numeric format with "
        "day <= 12 dates (numeric_stress). With label-free clusters of low purity it recovers part of them and can mis-pool suppliers "
        "that print opposite orders (the `wrong` column): every such date carries the flag `date_order_inferred` and must take the "
        "Phase 5 confidence penalty. Dates left raw keep the flag `date_ambiguous`."
    )
    L.append("")
    L.append(
        "### R2 detail: SYNTHETIC number variants (gold totals / first 3 quantities per doc re-printed)"
    )
    L.append("")
    L.append(
        "| field / printed variant | n | scorer-correct untouched | scorer-correct after normalize_number | digits altered (must be 0) |"
    )
    L.append("|---|---|---|---|---|")
    for k, v in res["number_synthetic"].items():
        L.append(
            f"| {k} | {v['n']} | {v['raw_correct']} | {v['normalized_correct']} | {v['digits_altered']} |"
        )
    L.append("")
    L.append(
        "Limitation: a European integer quantity printed with a dot as thousands separator (`1.234`) is indistinguishable from the "
        "decimal 1.234; it is kept as printed with the flag `number_dot_three_decimals` (the quantity / decimal_comma rows above: "
        "untouched = after). A decimal-comma total with a currency suffix is resolved."
    )
    L.append("")
    L.append("### R6 detail: OCR labelled-total pointer (invoices of dev100)")
    L.append("")
    L.append("`" + json.dumps(res["total_pointer"], sort_keys=True) + "`")
    L.append("")
    L.append("### G3 decision")
    L.append("")
    L.extend(meta["decision_lines"])
    L.append("")
    return "\n".join(L)


def decision_lines(res: dict[str, Any]) -> list[str]:
    """Per-rule and overall G3 text from the measured numbers (no hand-typed metrics)."""
    rungs = {r["id"]: r for r in res["ladder"]["rungs"]}
    loo = {r["id"]: r for r in res["ladder"]["loo"]}
    ev_ = res["merge_events"]
    syn = res["date_synthetic"]["numeric_stress"]
    support = {
        "R1a": "per-document resolution recovers every gold date re-printed in the 5 seen formats (SYNTHETIC)",
        "R1b": (
            f"SYNTHETIC numeric_stress: per-document {syn['per_document']['correct']}/384, predicted clusters "
            f"{syn['predicted_cluster']['correct']}/384 correct with {syn['predicted_cluster'].get('wrong', 0)} wrong "
            f"(flagged date_order_inferred), oracle groups {syn['oracle_group']['correct']}/384; seen formats: no gain"
        ),
        "R2": "SYNTHETIC: needed for every non-comma format (see R2 detail); digits never altered",
        "R2b": "convention evidenced in recon section 4 (gold keeps the 3-letter code only)",
        "R5": (
            f"page-2 trap instances in dev100: {ev_['ignored_elsewhere_docs']} docs; docs with disagreeing pages: "
            f"{ev_['disagree_docs']}; covered by tests/test_merge.py"
        ),
        "R6": "pointer agrees with the last-page value choice (see R6 detail); differs from R5 only if a later page has a value but no label",
        "R7": f"docs with a repeated header row in this run: {ev_['docs_with_header_rows']}; covered by tests/test_merge.py",
        "R8": f"docs with all-null rows in this run: {ev_['docs_with_null_rows']} (they were frequent in the compact-format spike40 traces)",
    }
    out = [
        "| rule | verdict by the spec gate | cells changed (gain/loss docs) | disposition |",
        "|---|---|---|---|",
    ]
    for rid, label, _ in STEPS:
        s = rungs[rid]
        verdict = kept_decision(rid, s)
        ch = s["changes_vs_prev"]
        n_changed = sum(ch.values())
        gains = sum(v["gain"] for v in s["header_flips_vs_prev"].values())
        losses = sum(v["loss"] for v in s["header_flips_vs_prev"].values())
        d = loo[rid]["full_minus_without"]["OVERALL"]
        if verdict.startswith("KEEP"):
            disp = "KEPT (measured; re-measure on 500-doc OOF)"
        elif verdict.startswith("DROP"):
            disp = "DROPPED (measured harm)"
        elif n_changed == 0:
            disp = (
                "NO MEASURED EFFECT (0 values changed: nothing for it to fix in this output). "
                f"Retained as a fail-closed safety net for unseen suppliers, benefit NOT claimed; evidence = {support[rid]}"
            )
        elif gains and not losses:
            disp = (
                f"GATE NOT MET (CI includes 0; point {100 * d['delta']:+.2f}) but every score flip is a gain and none a loss. "
                f"Retained, flagged borderline; Step U decides; evidence = {support[rid]}"
            )
        else:
            disp = (
                f"SCORER-NEUTRAL on dev100 ({n_changed} cell values re-formatted, 0 score flips). "
                f"Retained as a safety net, benefit NOT claimed; evidence = {support[rid]}"
            )
        out.append(
            f"| {rid} {label} | {verdict}; loo d={100 * d['delta']:+.2f} {ci_str(d['lo'], d['hi'])} | "
            f"{n_changed} cells ({gains}/{losses}) | {disp} |"
        )
    out.append("")
    inv = res["no_invention"]
    out.append(
        f"Fail-closed check on the dev100 outputs: of {inv['changed_cells']} cells changed by the value-changing rules (R0 -> R8), "
        f"{inv['violations']} are not a re-formatting of the raw value (digits changed, or the new value not contained in the raw one). "
        "R3/R4 return flags only (asserted: predictions byte-identical before/after validation)."
    )
    out.append("")
    vd = res["validators"]
    out.append(
        "R3 / R4 (confidence features): KEPT as inputs to the later confidence model; their informativeness on REAL errors is NOT ASSESSABLE "
        f"on dev100 (wrong non-null values per flag: currency {vd['R3 currency (ISO 4217)']['wrong']}, "
        f"airports {vd['R3 airports (IATA)']['wrong']}, AWB {vd['R4 AWB shape (awb_number, mawb)']['wrong']}, "
        f"HAWB {vd['R4 HAWB shape']['wrong']}; the criterion needs >= 5). "
        "Support: no false alarms on the gold values of train+dev (table above) and 100% catch of injected format-breaking errors. "
        "Limitation: same-class digit/letter substitutions are not caught by the shape checks (AWB/HAWB) and only partly by IATA membership, "
        "so these flags detect structural misreads, not wrong-but-well-formed values."
    )
    out.append("")
    r8 = rungs["R8"]["vs_R0"]["OVERALL"]
    out.append(
        f"Overall G3 (full pipeline R8 vs R0): d OVERALL = {100 * r8['delta']:+.2f} {ci_str(r8['lo'], r8['hi'])}, false-fill "
        f"{pct(rungs['R0']['false_fill'])} -> {pct(rungs['R8']['false_fill'])}; CI excludes 0: {'yes' if excludes_0(r8) else 'NO'}. "
        "The strict spec gate is therefore NOT met by Phase 3 as a whole on dev100. The pipeline is retained because the only measured "
        "movement is a gain with no loss and the remaining rules are no-ops on this model's output (safety nets), not because a "
        "benefit was demonstrated; Step U (500 docs) re-gates."
    )
    return out


def merge_events(ctx: Ctx, gold: dict[str, Any]) -> dict[str, int]:
    """How often the merge situations the rules target occur in this run (docs)."""
    c: Counter[str] = Counter()
    for d in gold:
        pages = ctx.pages[d]
        m = merge_pages(pages, ctx.prov).diffs
        c["ignored_elsewhere_docs"] += bool(m["ignored_elsewhere"])
        c["disagree_docs"] += bool(m["disagreement"])
        c["docs_with_header_rows"] += bool(m["dropped_header_rows"])
        c["docs_with_null_rows"] += bool(m["dropped_null_rows"])
        c["waybill_docs_with_rows"] += bool(m["dropped_waybill_rows"])
        c["doc_type_disagree_docs"] += len(m["doc_type_votes"]) > 1
        c["multipage_docs"] += len(pages) > 1
    return dict(c)


def no_invention(pa: dict[str, Any], pb: dict[str, Any]) -> dict[str, int]:
    """Every cell changed between two prediction sets must be a re-formatting of the old value.

    OK means: the new value is contained in the old one (airport city strip, code case), or both
    carry the same non-empty digit sequence (number separators / symbols), or - for a date - the
    new value is a valid ISO date whose year digits occur in the old value.
    """
    changed = bad = 0

    def digits(x: str) -> str:
        return re.sub(r"\D", "", x)

    def check(field: str, old: Any, new: Any) -> None:
        nonlocal changed, bad
        if old == new:
            return
        changed += 1
        o, n = str(old), str(new)
        ok = n.upper() in o.upper() or (digits(o) != "" and digits(o) == digits(n))
        if field == "invoice_date":
            ok = ok or (re.fullmatch(r"\d{4}-\d{2}-\d{2}", n) is not None and n[:4] in o)
        bad += not ok

    for d, a in pa.items():
        b = pb[d]
        for k in a["header"]:
            check(k, a["header"][k], b["header"].get(k))
        for ra, rb in zip(a["line_items"], b["line_items"], strict=False):
            for k in ra:
                check(k, ra[k], rb.get(k))
    return {"changed_cells": changed, "violations": bad}


def merge_block(text: str, md: str, begin: str = BEGIN, end: str = END) -> str:
    """`text` with the block between `begin` / `end` replaced by `md` (appended if absent). Any
    other marked block, and everything outside the markers, stays byte-identical."""
    block = f"{begin}\n{md}\n{end}\n"
    if begin in text and end in text:
        head, rest = text.split(begin, 1)
        tail = rest.split(end, 1)[1].lstrip("\n")
        return head + block + tail
    return text.rstrip("\n") + "\n\n" + block


def write_report(md: str, begin: str = BEGIN, end: str = END) -> None:
    """Create reports/ablations.md or replace only the block marked by `begin` / `end`."""
    path = ROOT / "reports" / "ablations.md"
    if path.is_file():
        text = merge_block(path.read_text(encoding="utf-8"), md, begin, end)
    else:
        text = merge_block("# Ablations and gate decisions\n", md, begin, end)
    path.write_text(text, encoding="utf-8", newline="\n")


# ------------------------------------------------------------------------------ 500-doc re-gate


def select_docs(corp: list[Any], doc_ids: list[str]) -> dict[str, Any]:
    """The corpus records (train+dev) of the traced docs, in trace order.

    Fails closed: a traced doc missing from the corpus, or a duplicate doc id, raises instead of
    silently scoring a subset."""
    if len(set(doc_ids)) != len(doc_ids):
        raise ValueError("duplicate doc_id in the trace")
    by_id = {r.doc_id: r for r in corp}
    missing = [d for d in doc_ids if d not in by_id]
    if missing:
        raise ValueError(f"{len(missing)} traced docs are not in the train+dev corpus")
    return {d: by_id[d] for d in doc_ids}


def differing_docs(pa: dict[str, Any], pb: dict[str, Any]) -> list[str]:
    """Doc ids whose predictions differ (a doc missing from `pb` counts as different)."""
    return [d for d in pa if pb.get(d) != pa[d]]


def explain_differences(
    ctx: Ctx, saved: dict[str, Any], base: Rules, doc_ids: list[str]
) -> dict[str, int]:
    """For docs where `base` != `saved`: which single rule, switched off, restores `saved`.

    The first rule (ladder order) that explains a doc gets it; the rest are ``unexplained``.
    Counts only."""
    by_rule: Counter[str] = Counter()
    for d in doc_ids:
        for rid, _, fld in STEPS:
            if getattr(base, fld) and run_doc(d, replace(base, **{fld: False}), ctx)[0] == saved[d]:
                by_rule[rid] += 1
                break
        else:
            by_rule["unexplained"] += 1
    return dict(by_rule)


def slice_rows(
    p0: dict[str, Any], p8: dict[str, Any], gold: dict[str, Any], recs: dict[str, Any]
) -> list[dict[str, Any]]:
    """R0 vs R8 on subsets of the docs: all, doc type, scanned / digital, train / dev."""
    defs: list[tuple[str, Any]] = [
        ("all", lambda r: True),
        ("invoices", lambda r: r.doc_type == "invoice"),
        ("waybills", lambda r: r.doc_type == "waybill"),
        ("scanned", lambda r: r.scanned),
        ("digital", lambda r: not r.scanned),
        ("train docs", lambda r: r.split == "train"),
        ("dev docs", lambda r: r.split == "dev"),
    ]
    out = []
    for name, keep in defs:
        ids = [d for d in gold if keep(recs[d])]
        if not ids:
            continue
        g = {d: gold[d] for d in ids}
        a, b = {d: p0[d] for d in ids}, {d: p8[d] for d in ids}
        out.append(
            {
                "slice": name,
                "n": len(ids),
                "R0": point(a, g),
                "R8": point(b, g),
                "paired": paired(a, b, g),
            }
        )
    return out


def git_short_head() -> str:
    """Short sha of the repo HEAD ('?' if git is unavailable)."""
    try:
        r = subprocess.run(  # noqa: S603 - fixed argv, read-only
            ["git", "rev-parse", "--short", "HEAD"],  # noqa: S607
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return r.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "?"


def gate_word(verdict: str) -> str:
    """PASS gate / FAIL gate from a `kept_decision` verdict (KEEP = pass)."""
    return "PASS gate" if verdict.startswith("KEEP") else "FAIL gate"


def validator_criterion(v: dict[str, Any]) -> str:
    """Spec criterion for a confidence flag on real errors: n_wrong >= 5, recall >= 50%, precision
    >= 2x the base error rate."""
    if v["wrong"] < 5:
        return f"n_wrong {v['wrong']} < 5: NOT ASSESSABLE"
    rec, prec, base = v["recall_of_errors"], v["flag_precision"], v["base_error_rate"]
    ok = rec is not None and rec >= 0.5 and prec is not None and prec >= 2 * base
    return f"n_wrong {v['wrong']} >= 5: criterion {'MET' if ok else 'NOT met'}"


def decision_lines_500(res: dict[str, Any]) -> list[str]:
    """Per-rule and overall G3 text of the 500-doc re-gate from the measured numbers."""
    rungs = {r["id"]: r for r in res["ladder"]["rungs"]}
    loo = {r["id"]: r for r in res["ladder"]["loo"]}
    ev_ = res["merge_events"]
    support = {
        "R1a": f"model dates already ISO in {res['dates']['iso']}/{res['dates']['total']} docs",
        "R1b": "label-free cluster order; SYNTHETIC evidence in the dev100 block",
        "R2": "SYNTHETIC evidence in the dev100 block; digits never altered",
        "R2b": "convention evidenced in recon section 4 (gold keeps the 3-letter code only)",
        "R5": f"docs with ignored-elsewhere values {ev_['ignored_elsewhere_docs']}, disagreeing pages {ev_['disagree_docs']}",
        "R6": "pointer vs last-page choice, see the pointer line above",
        "R7": f"docs with a repeated header row: {ev_['docs_with_header_rows']}",
        "R8": f"docs with all-null rows: {ev_['docs_with_null_rows']}",
    }
    out = [
        "| rule | gate | verdict by the spec gate | cells changed (gain/loss docs) | disposition |",
        "|---|---|---|---|---|",
    ]
    for rid, label, _ in STEPS:
        s = rungs[rid]
        verdict = kept_decision(rid, s)
        n_changed = sum(s["changes_vs_prev"].values())
        gains = sum(v["gain"] for v in s["header_flips_vs_prev"].values())
        losses = sum(v["loss"] for v in s["header_flips_vs_prev"].values())
        d = loo[rid]["full_minus_without"]["OVERALL"]
        if verdict.startswith("KEEP"):
            disp = "KEPT (measured on unseen docs)"
        elif verdict.startswith("DROP"):
            disp = "MEASURED HARM: remove from the default pipeline"
        elif n_changed == 0:
            disp = (
                "NO MEASURED EFFECT (0 values changed). Retained as a fail-closed safety net, "
                f"benefit NOT claimed; evidence = {support[rid]}"
            )
        elif losses:
            disp = (
                f"GATE NOT MET and {losses} score losses against {gains} gains; "
                f"needs a decision; evidence = {support[rid]}"
            )
        elif gains:
            disp = (
                f"GATE NOT MET (CI includes 0; loo point {100 * d['delta']:+.2f}) but every score "
                f"flip is a gain and none a loss. Retained, flagged borderline; evidence = {support[rid]}"
            )
        else:
            disp = (
                f"SCORER-NEUTRAL ({n_changed} cell values re-formatted, 0 score flips). "
                f"Retained as a safety net, benefit NOT claimed; evidence = {support[rid]}"
            )
        out.append(
            f"| {rid} {label} | {gate_word(verdict)} | {verdict}; loo d={100 * d['delta']:+.2f} {ci_str(d['lo'], d['hi'])} | "
            f"{n_changed} cells ({gains}/{losses}) | {disp} |"
        )
    out.append("")
    vd = res["validators"]
    crit = "; ".join(
        f"{k}: {validator_criterion(v)}"
        for k, v in vd.items()
        if k != "gold_false_alarms_train_dev"
    )
    out.append(f"R3 / R4 (confidence-only, no rung): {crit}.")
    out.append("")
    r8 = rungs["R8"]["vs_R0"]
    whole = kept_decision("R8", {"vs_prev": r8})
    out.append(
        f"Overall G3 (full pipeline R8 vs R0, 500 docs): d OVERALL = {100 * r8['OVERALL']['delta']:+.2f} "
        f"{ci_str(r8['OVERALL']['lo'], r8['OVERALL']['hi'])}, false-fill {pct(rungs['R0']['false_fill'])} -> "
        f"{pct(rungs['R8']['false_fill'])}; CI excludes 0: {'yes' if excludes_0(r8['OVERALL']) else 'NO'}; "
        f"verdict: {whole} => {gate_word(whole)}."
    )
    return out


def build_markdown_500(res: dict[str, Any], meta: dict[str, Any]) -> str:
    """The 500-doc re-gate section (aggregates only; no gold or predicted values)."""
    L: list[str] = []
    rungs = res["ladder"]["rungs"]
    f1 = lambda x: "n/a" if x is None else f"{100 * x:.1f}%"  # noqa: E731
    L.append(f"## {SECTION_500}")
    L.append("")
    L.append(
        f"**Every number below is UNVERIFIED** (the verifier recomputes them). Provenance: run `{meta['run']}`, manifest code_sha "
        f"`{meta['code_sha']}`, trace git_commit `{meta['code']}`, repo HEAD `{meta['head']}`, command `{meta['command']}`. "
        f"n = {meta['n_docs']} docs ({meta['n_train']} train + {meta['n_dev']} dev), image-only keyed Qwen3.5-4B zero-shot, "
        f"decided on unseen results (spec section 5); paired document-level bootstrap, {N_BOOT} resamples, seed {SEED}, "
        "`shipdoc.eval.paired_bootstrap`; scorer unmodified. Deltas are in OVERALL points (x100)."
    )
    L.append("")
    L.append(
        "Method notes. Pages go through `shipdoc.coerce.page_for_merge` and every rung's document through `coerce_doc` + `repair_doc`, "
        "the run writer's own path. R0 is defined as in the dev100 block above. The R1b layout clusters and the R6 pointer use OCR "
        f"only; the cluster fit set ({res['clusters']['n_fit']} train+dev invoice page-1 signatures, label-free) OVERLAPS the evaluated "
        "docs: no label is used, but the cluster of a doc was fit with that doc's own layout signature, so the R1b measurement is not "
        f"held out in the layout sense. Parse failures in this run: {meta['parse_failures']} pages. "
        "Synthetic sections (R1 / R2 mechanism, injection) are not re-run; see the dev100 block."
    )
    L.append("")
    L.append("### (a) Cumulative ladder")
    L.append("")
    L.append(
        "| step | rule | OVERALL [95% CI] | false-fill rate [95% CI] | d vs previous [CI] | d vs R0 [CI] | values changed vs previous | G3 verdict | gate |"
    )
    L.append("|---|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(rungs):
        ci = f"{pct(r['OVERALL'])} [{pct(r['OVERALL_ci'][0])}, {pct(r['OVERALL_ci'][1])}]"
        ff = f"{pct(r['false_fill'])} [{pct(r['false_fill_ci'][0])}, {pct(r['false_fill_ci'][1])}]"
        if i == 0:
            L.append(f"| R0 | {r['label']} | {ci} | {ff} | - | - | - | - | - |")
            continue
        p, z = r["vs_prev"]["OVERALL"], r["vs_R0"]["OVERALL"]
        chs = ", ".join(f"{k}:{v}" for k, v in sorted(r["changes_vs_prev"].items())) or "none"
        v = kept_decision(r["id"], r)
        L.append(
            f"| {r['id']} | {r['label']} | {ci} | {ff} | {100 * p['delta']:+.2f} {ci_str(p['lo'], p['hi'])} | "
            f"{100 * z['delta']:+.2f} {ci_str(z['lo'], z['hi'])} | {chs} | {v} | {gate_word(v)} |"
        )
    L.append("")
    L.append(f"Baseline consistency (R8 vs the run's own `predictions.json`): {meta['repro']}")
    L.append("")
    L.append("### (b) Leave-one-out (full pipeline minus one rule)")
    L.append("")
    L.append(
        "| rule | OVERALL without | d (full - without) [CI] | values changed | CI excludes 0 |"
    )
    L.append("|---|---|---|---|---|")
    for r in res["ladder"]["loo"]:
        d = r["full_minus_without"]["OVERALL"]
        chs = ", ".join(f"{k}:{v}" for k, v in sorted(r["changes"].items())) or "none"
        L.append(
            f"| {r['id']} {r['label']} | {pct(r['OVERALL_without'])} | {100 * d['delta']:+.2f} {ci_str(d['lo'], d['hi'])} | {chs} | {'yes' if excludes_0(d) else 'no'} |"
        )
    L.append("")
    L.append(
        "### (c) Per-field effects (docs whose field went wrong->right / right->wrong, vs previous rung)"
    )
    L.append("")
    L.append("| step | header fields | row effect (correct rows / predicted rows) |")
    L.append("|---|---|---|")
    for r in rungs[1:]:
        fl = (
            ", ".join(
                f"{k}: +{v['gain']}/-{v['loss']}"
                for k, v in sorted(r["header_flips_vs_prev"].items())
            )
            or "no field changed"
        )
        re_ = r["row_effect_vs_prev"]
        L.append(f"| {r['id']} | {fl} | {re_['rows_full']:+d} / {re_['rows_pred']:+d} |")
    L.append("")
    r0, rf = rungs[0], rungs[-1]
    L.append("Header accuracy by field, R0 -> R8:")
    L.append("")
    L.append("| field | R0 | R8 |")
    L.append("|---|---|---|")
    for k in sorted(rf["header_by_field"]):
        L.append(f"| {k} | {pct(r0['header_by_field'][k])} | {pct(rf['header_by_field'][k])} |")
    L.append("")
    L.append("### (d) Slices, R0 vs R8")
    L.append("")
    L.append(
        "| slice | n | OVERALL R0 [CI] | OVERALL R8 [CI] | d R8 - R0 [CI] | false-fill R0 -> R8 | d false-fill [CI] | CI excludes 0 |"
    )
    L.append("|---|---|---|---|---|---|---|---|")
    for s in res["slices"]:
        a, b, p = s["R0"], s["R8"], s["paired"]
        o, f = p["OVERALL"], p["false_fill_rate"]
        L.append(
            f"| {s['slice']} | {s['n']} | {pct(a['OVERALL'])} [{pct(a['OVERALL_ci'][0])}, {pct(a['OVERALL_ci'][1])}] | "
            f"{pct(b['OVERALL'])} [{pct(b['OVERALL_ci'][0])}, {pct(b['OVERALL_ci'][1])}] | {100 * o['delta']:+.2f} {ci_str(o['lo'], o['hi'])} | "
            f"{pct(a['false_fill'])} -> {pct(b['false_fill'])} | {100 * f['delta']:+.2f} {ci_str(f['lo'], f['hi'])} | {'yes' if excludes_0(o) else 'no'} |"
        )
    L.append("")
    L.append("### (e) Confidence-only rules R3 / R4 (predictions of the R8 rung)")
    L.append("")
    L.append(
        "Criterion for KEEP as a confidence feature: on real errors, n_wrong >= 5, recall of errors >= 50% and flag precision >= 2x the "
        "base error rate; with fewer than 5 real errors the flag is NOT ASSESSABLE on real data. Flags cannot change a value (asserted)."
    )
    L.append("")
    L.append(
        "| flag | values | wrong | base error rate | flagged | flagged & wrong | recall of errors | flag precision | false-alarm rate (flagged / correct) [Wilson 95%] | n_wrong >= 5 criterion |"
    )
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for g, v in res["validators"].items():
        if g == "gold_false_alarms_train_dev":
            continue
        lo, hi = v["false_alarm_wilson"]
        L.append(
            f"| {g} | {v['n']} | {v['wrong']} | {f1(v['base_error_rate'])} | {v['flagged']} | {v['flagged_wrong']} | {f1(v['recall_of_errors'])} | {f1(v['flag_precision'])} | "
            f"{v['flagged_right']}/{v['n'] - v['wrong']} = {f1(v['false_alarm_rate'])} [{100 * lo:.1f}, {100 * hi:.1f}] | {validator_criterion(v)} |"
        )
    L.append("")
    L.append("False alarms on the GOLD values of all 500 train+dev docs:")
    L.append("")
    L.append("| flag | gold values | flagged | false-alarm rate |")
    L.append("|---|---|---|---|")
    for g, v in res["validators"]["gold_false_alarms_train_dev"].items():
        L.append(f"| {g} | {v['n']} | {v['flagged']} | {100 * v['flagged'] / v['n']:.2f}% |")
    L.append("")
    cl = res["clusters"]
    L.append("### R1 / R6 detail")
    L.append("")
    L.append(
        f"Layout clusters: k={cl['k']} (silhouette {cl['silhouette']:.3f}), fit on {cl['n_fit']} invoice page-1 signatures without labels, "
        f"ARI vs supplier group {cl['ari']:.3f}, purity {cl['purity']:.3f}. Model dates already ISO in {res['dates']['iso']}/{res['dates']['total']} docs. "
        f"OCR labelled-total pointer (invoices): `{json.dumps(res['total_pointer'], sort_keys=True)}`"
    )
    L.append("")
    L.append("### G3 decision (500-doc zero-shot, train+dev)")
    L.append("")
    L.append(
        "Gate (spec section 5, as implemented by `kept_decision`): a rule PASSES if the 95% CI of its OVERALL delta vs the previous rung "
        "excludes 0, OR OVERALL does not fall while false-fill falls; otherwise FAIL gate."
    )
    L.append("")
    L.extend(meta["decision_lines"])
    L.append("")
    return "\n".join(L)


def finish_500(
    args: argparse.Namespace,
    traces: list[dict[str, Any]],
    ctx: Ctx,
    lad: dict[str, Any],
    saved: dict[str, Any],
    gold: dict[str, Any],
    recs: dict[str, Any],
    raw: dict[str, str | None],
    corp: list[Any],
    cl_stats: dict[str, Any],
) -> int:
    """Everything after the ladder in ``--docs train+dev`` mode: baseline-consistency check,
    slices, flags, report block `G3-500` (the dev100 block is never touched)."""
    preds = lad["preds"]
    full = preds["R8"]
    base = replace(FULL, total_ocr=False, cluster_dates=False)  # == the run's own merge defaults
    default_equiv = run_all(base, ctx)
    n = len(saved)
    d_default = differing_docs(default_equiv, saved)
    d_full = differing_docs(full, saved)
    # the same rungs WITHOUT the writer's coerce + schema-repair step (float numbers, raw dates)
    ctx_raw = copy.copy(ctx)
    ctx_raw.finalize = False
    ctx_raw.pages = {
        t["doc_id"]: [parse_output(p["raw_text"], "json") for p in t["pages"]] for t in traces
    }
    d_nofinal = differing_docs(run_all(base, ctx_raw), saved)
    why_default = explain_differences(ctx, saved, base, d_default) if d_default else {}
    why_full = explain_differences(ctx, saved, FULL, d_full) if d_full else {}
    repro = (
        f"R8 minus R6/R1b == saved predictions.json: {not d_default} ({len(d_default)} of {n} docs differ"
        f"{'; first rule that explains them: ' + json.dumps(why_default, sort_keys=True) if d_default else ''}); "
        f"R8 (with R6/R1b) == saved: {not d_full} ({len(d_full)} of {n} docs differ"
        f"{'; first rule that explains them: ' + json.dumps(why_full, sort_keys=True) if d_full else ''}); "
        f"same check without the writer's page_for_merge + coerce_doc + repair_doc step: "
        f"{len(d_nofinal)} of {n} docs differ"
    )
    assert (
        ev.score(full, gold)["all"]["OVERALL"]
        == ev.score(json.loads(json.dumps(full)), gold)["all"]["OVERALL"]
    )
    date_vals = [v for v in raw.values() if v]
    res = {
        "ladder": {k: v for k, v in lad.items() if k != "preds"},
        "validators": validator_report(full, gold, [r.gold for r in corp]),
        "clusters": cl_stats,
        "slices": slice_rows(preds["R0"], full, gold, recs),
        "total_pointer": total_pointer_stats(ctx, gold, full),
        "merge_events": merge_events(ctx, gold),
        "no_invention": no_invention(preds["R0"], full),
        "dates": {
            "iso": sum(bool(re.fullmatch(r"\d{4}-\d{2}-\d{2}", v)) for v in date_vals),
            "total": len(date_vals),
        },
    }
    manifest_path = args.run_dir / "manifest.json"
    code_sha = json.loads(manifest_path.read_text(encoding="utf-8")).get("code_sha", "?")
    meta: dict[str, Any] = {
        "run": args.run_dir.name,
        "code": traces[0].get("git_commit", "?"),
        "code_sha": code_sha,
        "head": git_short_head(),
        "command": "uv run python scripts/postproc_ablation.py " + " ".join(sys.argv[1:]),
        "n_docs": len(gold),
        "n_train": sum(r.split == "train" for r in recs.values()),
        "n_dev": sum(r.split == "dev" for r in recs.values()),
        "parse_failures": sum(p is None for pages in ctx.pages.values() for p in pages),
        "repro": repro,
        "r8_equals_saved": {"default_equiv": not d_default, "full": not d_full},
    }
    meta["decision_lines"] = decision_lines_500(res)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "postproc_ablation_500.json").write_text(
        json.dumps({"meta": meta, **res}, indent=1, default=str), encoding="utf-8"
    )
    md = build_markdown_500(res, meta)
    (args.out_dir / "postproc_ablation_500.md").write_text(md, encoding="utf-8")
    if args.write_report:
        tag = getattr(args, "report_tag", "") or ""
        if tag:  # a second 500-doc run (e.g. native resolution) gets its own block, never the first
            md = md.replace(f"## {SECTION_500}", f"## {SECTION_500}, {tag}", 1)
        write_report(md, *markers_500(tag))
    print(md)
    return 0


# ------------------------------------------------------------------------------ main


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--run-dir", type=Path, default=paths.runs_dir() / DEFAULT_RUN)
    ap.add_argument(
        "--out-dir", type=Path, default=paths.runs_dir() / "diagnosis" / "postproc_ablation"
    )
    ap.add_argument("--labels", type=Path, default=None, help="default: <data>/dev/labels")
    ap.add_argument("--write-report", action="store_true")
    ap.add_argument(
        "--docs",
        choices=("dev", "train+dev"),
        default="dev",
        help="dev: the dev100 run (default); train+dev: a 500-doc run, own report block",
    )
    ap.add_argument(
        "--report-tag",
        default="",
        help="train+dev with --write-report: write a separate tagged block (e.g. 'native "
        "resolution') instead of replacing the default 500-doc block",
    )
    args = ap.parse_args(argv)
    full_mode = args.docs == "train+dev"

    traces = read_trace(args.run_dir / "trace.jsonl")
    corp = load_corpus()
    recs: dict[str, Any] = {}
    if full_mode:
        recs = select_docs(corp, [t["doc_id"] for t in traces])
        gold = {d: r.gold for d, r in recs.items()}
    else:
        gold = ev.load_gold(args.labels or paths.data_dir() / "dev" / "labels")
        gold = {d: gold[d] for d in (t["doc_id"] for t in traces)}
    saved = json.loads((args.run_dir / "predictions.json").read_text(encoding="utf-8"))

    # Label-free layout clusters: fit on train+dev invoice page-1 OCR (never test).
    inv = [r for r in corp if r.doc_type == "invoice"]
    sig = {r.doc_id: layout_signature(r.pages()[0]) for r in inv}
    clusters = LayoutClusters.fit([sig[r.doc_id] for r in inv])
    cl_ids = dict(
        zip((r.doc_id for r in inv), clusters.predict([sig[r.doc_id] for r in inv]), strict=True)
    )
    from sklearn.metrics import adjusted_rand_score

    ari = float(adjusted_rand_score([r.group for r in inv], [cl_ids[r.doc_id] for r in inv]))
    by_c: dict[int, Counter[str]] = defaultdict(Counter)
    for r in inv:
        by_c[cl_ids[r.doc_id]][r.group] += 1
    purity = sum(max(c.values()) for c in by_c.values()) / len(inv)

    ctx = Ctx(traces, finalize=full_mode)
    raw = raw_dates(ctx)
    pools: dict[int, list[str]] = defaultdict(list)
    for d, v in raw.items():
        if v and d in cl_ids:
            pools[cl_ids[d]].append(v)
    orders = {c: infer_date_order(v) for c, v in pools.items()}
    ctx.date_order = {d: orders.get(cl_ids.get(d, -1)) for d in raw}

    lad = ladder(ctx, gold)
    full = lad["preds"]["R8"]
    if full_mode:
        cl_stats = {
            "k": clusters.k,
            "silhouette": clusters.silhouette,
            "n_fit": len(inv),
            "ari": ari,
            "purity": purity,
        }
        return finish_500(args, traces, ctx, lad, saved, gold, recs, raw, corp, cl_stats)
    # Reproduction check: R8 without R6/R1b is exactly the shipped merge+normalize default.
    default_equiv = run_all(replace(FULL, total_ocr=False, cluster_dates=False), ctx)
    repro = (
        "R8 minus R6/R1b == saved predictions.json: "
        + str(default_equiv == saved)
        + f"; R8 == saved: {full == saved}"
    )
    # R3 / R4 cannot move a score: predictions are unchanged by construction; re-score to show it.
    assert (
        ev.score(full, gold)["all"]["OVERALL"]
        == ev.score(json.loads(json.dumps(full)), gold)["all"]["OVERALL"]
    )
    corpus_gold = [r.gold for r in corp]
    res = {
        "ladder": {k: v for k, v in lad.items() if k != "preds"},
        "validators": validator_report(full, gold, corpus_gold),
        "injection": validator_injection(corpus_gold),
        "clusters": {
            "k": clusters.k,
            "silhouette": clusters.silhouette,
            "n_fit": len(inv),
            "ari": ari,
            "purity": purity,
        },
        "date_synthetic": date_synthetic(corp, cl_ids),
        "number_synthetic": number_synthetic(gold),
        "total_pointer": total_pointer_stats(ctx, gold, full),
        "merge_events": merge_events(ctx, gold),
        "no_invention": no_invention(lad["preds"]["R0"], full),
    }
    date_vals = [v for v in raw.values() if v]
    meta = {
        "run": str(args.run_dir.relative_to(paths.runs_dir()))
        if args.run_dir.is_relative_to(paths.runs_dir())
        else args.run_dir.name,
        "code": traces[0].get("git_commit", "?"),
        "n_docs": len(gold),
        "parse_failures": sum(p is None for pages in ctx.pages.values() for p in pages),
        "repro": repro,
        "date_iso": sum(bool(re.fullmatch(r"\d{4}-\d{2}-\d{2}", v)) for v in date_vals),
        "date_total": len(date_vals),
    }
    meta["decision_lines"] = decision_lines(res)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "postproc_ablation.json").write_text(
        json.dumps({"meta": meta, **res}, indent=1, default=str), encoding="utf-8"
    )
    md = build_markdown(res, meta)
    (args.out_dir / "postproc_ablation.md").write_text(md, encoding="utf-8")
    if args.write_report:
        write_report(md)
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
